/*
 * ASSIST_DEBUG.h
 * Debug Assist
 * Base Address: 0x600C2000
 */

#ifndef ASSIST_DEBUG_H
#define ASSIST_DEBUG_H

#include <stdint.h>

#define ASSIST_DEBUG_BASE 0x600C2000

// core0 monitor enable configuration register
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x0))
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_DRAM0_0_RD_ENA_M (0x00000001U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_DRAM0_0_RD_ENA_S (0)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_DRAM0_0_RD_ENA_V(v) (((v) << 0) & 0x00000001U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_DRAM0_0_WR_ENA_M (0x00000002U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_DRAM0_0_WR_ENA_S (1)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_DRAM0_0_WR_ENA_V(v) (((v) << 1) & 0x00000002U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_DRAM0_1_RD_ENA_M (0x00000004U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_DRAM0_1_RD_ENA_S (2)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_DRAM0_1_RD_ENA_V(v) (((v) << 2) & 0x00000004U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_DRAM0_1_WR_ENA_M (0x00000008U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_DRAM0_1_WR_ENA_S (3)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_DRAM0_1_WR_ENA_V(v) (((v) << 3) & 0x00000008U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_PIF_0_RD_ENA_M (0x00000010U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_PIF_0_RD_ENA_S (4)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_PIF_0_RD_ENA_V(v) (((v) << 4) & 0x00000010U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_PIF_0_WR_ENA_M (0x00000020U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_PIF_0_WR_ENA_S (5)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_PIF_0_WR_ENA_V(v) (((v) << 5) & 0x00000020U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_PIF_1_RD_ENA_M (0x00000040U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_PIF_1_RD_ENA_S (6)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_PIF_1_RD_ENA_V(v) (((v) << 6) & 0x00000040U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_PIF_1_WR_ENA_M (0x00000080U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_PIF_1_WR_ENA_S (7)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_AREA_PIF_1_WR_ENA_V(v) (((v) << 7) & 0x00000080U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_SP_SPILL_MIN_ENA_M (0x00000100U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_SP_SPILL_MIN_ENA_S (8)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_SP_SPILL_MIN_ENA_V(v) (((v) << 8) & 0x00000100U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_SP_SPILL_MAX_ENA_M (0x00000200U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_SP_SPILL_MAX_ENA_S (9)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_SP_SPILL_MAX_ENA_V(v) (((v) << 9) & 0x00000200U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_IRAM0_EXCEPTION_MONITOR_ENA_M (0x00000400U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_IRAM0_EXCEPTION_MONITOR_ENA_S (10)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_IRAM0_EXCEPTION_MONITOR_ENA_V(v) (((v) << 10) & 0x00000400U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_DRAM0_EXCEPTION_MONITOR_ENA_M (0x00000800U)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_DRAM0_EXCEPTION_MONITOR_ENA_S (11)
#define ASSIST_DEBUG_CORE_0_MONTR_ENA_CORE_0_DRAM0_EXCEPTION_MONITOR_ENA_V(v) (((v) << 11) & 0x00000800U)

// core0 monitor interrupt status register
#define ASSIST_DEBUG_CORE_0_INTR_RAW_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x4))
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_DRAM0_0_RD_RAW_M (0x00000001U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_DRAM0_0_RD_RAW_S (0)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_DRAM0_0_RD_RAW_V(v) (((v) << 0) & 0x00000001U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_DRAM0_0_WR_RAW_M (0x00000002U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_DRAM0_0_WR_RAW_S (1)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_DRAM0_0_WR_RAW_V(v) (((v) << 1) & 0x00000002U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_DRAM0_1_RD_RAW_M (0x00000004U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_DRAM0_1_RD_RAW_S (2)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_DRAM0_1_RD_RAW_V(v) (((v) << 2) & 0x00000004U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_DRAM0_1_WR_RAW_M (0x00000008U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_DRAM0_1_WR_RAW_S (3)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_DRAM0_1_WR_RAW_V(v) (((v) << 3) & 0x00000008U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_PIF_0_RD_RAW_M (0x00000010U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_PIF_0_RD_RAW_S (4)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_PIF_0_RD_RAW_V(v) (((v) << 4) & 0x00000010U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_PIF_0_WR_RAW_M (0x00000020U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_PIF_0_WR_RAW_S (5)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_PIF_0_WR_RAW_V(v) (((v) << 5) & 0x00000020U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_PIF_1_RD_RAW_M (0x00000040U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_PIF_1_RD_RAW_S (6)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_PIF_1_RD_RAW_V(v) (((v) << 6) & 0x00000040U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_PIF_1_WR_RAW_M (0x00000080U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_PIF_1_WR_RAW_S (7)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_AREA_PIF_1_WR_RAW_V(v) (((v) << 7) & 0x00000080U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_SP_SPILL_MIN_RAW_M (0x00000100U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_SP_SPILL_MIN_RAW_S (8)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_SP_SPILL_MIN_RAW_V(v) (((v) << 8) & 0x00000100U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_SP_SPILL_MAX_RAW_M (0x00000200U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_SP_SPILL_MAX_RAW_S (9)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_SP_SPILL_MAX_RAW_V(v) (((v) << 9) & 0x00000200U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_IRAM0_EXCEPTION_MONITOR_RAW_M (0x00000400U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_IRAM0_EXCEPTION_MONITOR_RAW_S (10)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_IRAM0_EXCEPTION_MONITOR_RAW_V(v) (((v) << 10) & 0x00000400U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_DRAM0_EXCEPTION_MONITOR_RAW_M (0x00000800U)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_DRAM0_EXCEPTION_MONITOR_RAW_S (11)
#define ASSIST_DEBUG_CORE_0_INTR_RAW_CORE_0_DRAM0_EXCEPTION_MONITOR_RAW_V(v) (((v) << 11) & 0x00000800U)

// core0 monitor interrupt enable register
#define ASSIST_DEBUG_CORE_0_INTR_ENA_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x8))
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_DRAM0_0_RD_INTR_ENA_M (0x00000001U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_DRAM0_0_RD_INTR_ENA_S (0)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_DRAM0_0_RD_INTR_ENA_V(v) (((v) << 0) & 0x00000001U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_DRAM0_0_WR_INTR_ENA_M (0x00000002U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_DRAM0_0_WR_INTR_ENA_S (1)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_DRAM0_0_WR_INTR_ENA_V(v) (((v) << 1) & 0x00000002U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_DRAM0_1_RD_INTR_ENA_M (0x00000004U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_DRAM0_1_RD_INTR_ENA_S (2)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_DRAM0_1_RD_INTR_ENA_V(v) (((v) << 2) & 0x00000004U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_DRAM0_1_WR_INTR_ENA_M (0x00000008U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_DRAM0_1_WR_INTR_ENA_S (3)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_DRAM0_1_WR_INTR_ENA_V(v) (((v) << 3) & 0x00000008U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_PIF_0_RD_INTR_ENA_M (0x00000010U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_PIF_0_RD_INTR_ENA_S (4)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_PIF_0_RD_INTR_ENA_V(v) (((v) << 4) & 0x00000010U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_PIF_0_WR_INTR_ENA_M (0x00000020U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_PIF_0_WR_INTR_ENA_S (5)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_PIF_0_WR_INTR_ENA_V(v) (((v) << 5) & 0x00000020U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_PIF_1_RD_INTR_ENA_M (0x00000040U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_PIF_1_RD_INTR_ENA_S (6)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_PIF_1_RD_INTR_ENA_V(v) (((v) << 6) & 0x00000040U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_PIF_1_WR_INTR_ENA_M (0x00000080U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_PIF_1_WR_INTR_ENA_S (7)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_AREA_PIF_1_WR_INTR_ENA_V(v) (((v) << 7) & 0x00000080U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_SP_SPILL_MIN_INTR_ENA_M (0x00000100U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_SP_SPILL_MIN_INTR_ENA_S (8)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_SP_SPILL_MIN_INTR_ENA_V(v) (((v) << 8) & 0x00000100U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_SP_SPILL_MAX_INTR_ENA_M (0x00000200U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_SP_SPILL_MAX_INTR_ENA_S (9)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_SP_SPILL_MAX_INTR_ENA_V(v) (((v) << 9) & 0x00000200U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_IRAM0_EXCEPTION_MONITOR_INTR_ENA_M (0x00000400U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_IRAM0_EXCEPTION_MONITOR_INTR_ENA_S (10)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_IRAM0_EXCEPTION_MONITOR_INTR_ENA_V(v) (((v) << 10) & 0x00000400U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_DRAM0_EXCEPTION_MONITOR_INTR_ENA_M (0x00000800U)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_DRAM0_EXCEPTION_MONITOR_INTR_ENA_S (11)
#define ASSIST_DEBUG_CORE_0_INTR_ENA_CORE_0_DRAM0_EXCEPTION_MONITOR_INTR_ENA_V(v) (((v) << 11) & 0x00000800U)

// core0 monitor interrupt clr register
#define ASSIST_DEBUG_CORE_0_INTR_CLR_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0xC))
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_DRAM0_0_RD_CLR_M (0x00000001U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_DRAM0_0_RD_CLR_S (0)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_DRAM0_0_RD_CLR_V(v) (((v) << 0) & 0x00000001U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_DRAM0_0_WR_CLR_M (0x00000002U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_DRAM0_0_WR_CLR_S (1)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_DRAM0_0_WR_CLR_V(v) (((v) << 1) & 0x00000002U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_DRAM0_1_RD_CLR_M (0x00000004U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_DRAM0_1_RD_CLR_S (2)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_DRAM0_1_RD_CLR_V(v) (((v) << 2) & 0x00000004U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_DRAM0_1_WR_CLR_M (0x00000008U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_DRAM0_1_WR_CLR_S (3)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_DRAM0_1_WR_CLR_V(v) (((v) << 3) & 0x00000008U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_PIF_0_RD_CLR_M (0x00000010U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_PIF_0_RD_CLR_S (4)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_PIF_0_RD_CLR_V(v) (((v) << 4) & 0x00000010U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_PIF_0_WR_CLR_M (0x00000020U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_PIF_0_WR_CLR_S (5)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_PIF_0_WR_CLR_V(v) (((v) << 5) & 0x00000020U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_PIF_1_RD_CLR_M (0x00000040U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_PIF_1_RD_CLR_S (6)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_PIF_1_RD_CLR_V(v) (((v) << 6) & 0x00000040U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_PIF_1_WR_CLR_M (0x00000080U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_PIF_1_WR_CLR_S (7)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_AREA_PIF_1_WR_CLR_V(v) (((v) << 7) & 0x00000080U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_SP_SPILL_MIN_CLR_M (0x00000100U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_SP_SPILL_MIN_CLR_S (8)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_SP_SPILL_MIN_CLR_V(v) (((v) << 8) & 0x00000100U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_SP_SPILL_MAX_CLR_M (0x00000200U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_SP_SPILL_MAX_CLR_S (9)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_SP_SPILL_MAX_CLR_V(v) (((v) << 9) & 0x00000200U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_IRAM0_EXCEPTION_MONITOR_CLR_M (0x00000400U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_IRAM0_EXCEPTION_MONITOR_CLR_S (10)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_IRAM0_EXCEPTION_MONITOR_CLR_V(v) (((v) << 10) & 0x00000400U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_DRAM0_EXCEPTION_MONITOR_CLR_M (0x00000800U)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_DRAM0_EXCEPTION_MONITOR_CLR_S (11)
#define ASSIST_DEBUG_CORE_0_INTR_CLR_CORE_0_DRAM0_EXCEPTION_MONITOR_CLR_V(v) (((v) << 11) & 0x00000800U)

// core0 dram0 region0 addr configuration register
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_0_MIN_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x10))
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_0_MIN_CORE_0_AREA_DRAM0_0_MIN_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_0_MIN_CORE_0_AREA_DRAM0_0_MIN_S (0)
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_0_MIN_CORE_0_AREA_DRAM0_0_MIN_V(v) (((v) << 0) & 0xFFFFFFFFU)

// core0 dram0 region0 addr configuration register
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_0_MAX_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x14))
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_0_MAX_CORE_0_AREA_DRAM0_0_MAX_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_0_MAX_CORE_0_AREA_DRAM0_0_MAX_S (0)
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_0_MAX_CORE_0_AREA_DRAM0_0_MAX_V(v) (((v) << 0) & 0xFFFFFFFFU)

// core0 dram0 region1 addr configuration register
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_1_MIN_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x18))
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_1_MIN_CORE_0_AREA_DRAM0_1_MIN_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_1_MIN_CORE_0_AREA_DRAM0_1_MIN_S (0)
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_1_MIN_CORE_0_AREA_DRAM0_1_MIN_V(v) (((v) << 0) & 0xFFFFFFFFU)

// core0 dram0 region1 addr configuration register
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_1_MAX_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x1C))
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_1_MAX_CORE_0_AREA_DRAM0_1_MAX_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_1_MAX_CORE_0_AREA_DRAM0_1_MAX_S (0)
#define ASSIST_DEBUG_CORE_0_AREA_DRAM0_1_MAX_CORE_0_AREA_DRAM0_1_MAX_V(v) (((v) << 0) & 0xFFFFFFFFU)

// core0 PIF region0 addr configuration register
#define ASSIST_DEBUG_CORE_0_AREA_PIF_0_MIN_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x20))
#define ASSIST_DEBUG_CORE_0_AREA_PIF_0_MIN_CORE_0_AREA_PIF_0_MIN_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_AREA_PIF_0_MIN_CORE_0_AREA_PIF_0_MIN_S (0)
#define ASSIST_DEBUG_CORE_0_AREA_PIF_0_MIN_CORE_0_AREA_PIF_0_MIN_V(v) (((v) << 0) & 0xFFFFFFFFU)

// core0 PIF region0 addr configuration register
#define ASSIST_DEBUG_CORE_0_AREA_PIF_0_MAX_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x24))
#define ASSIST_DEBUG_CORE_0_AREA_PIF_0_MAX_CORE_0_AREA_PIF_0_MAX_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_AREA_PIF_0_MAX_CORE_0_AREA_PIF_0_MAX_S (0)
#define ASSIST_DEBUG_CORE_0_AREA_PIF_0_MAX_CORE_0_AREA_PIF_0_MAX_V(v) (((v) << 0) & 0xFFFFFFFFU)

// core0 PIF region1 addr configuration register
#define ASSIST_DEBUG_CORE_0_AREA_PIF_1_MIN_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x28))
#define ASSIST_DEBUG_CORE_0_AREA_PIF_1_MIN_CORE_0_AREA_PIF_1_MIN_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_AREA_PIF_1_MIN_CORE_0_AREA_PIF_1_MIN_S (0)
#define ASSIST_DEBUG_CORE_0_AREA_PIF_1_MIN_CORE_0_AREA_PIF_1_MIN_V(v) (((v) << 0) & 0xFFFFFFFFU)

// core0 PIF region1 addr configuration register
#define ASSIST_DEBUG_CORE_0_AREA_PIF_1_MAX_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x2C))
#define ASSIST_DEBUG_CORE_0_AREA_PIF_1_MAX_CORE_0_AREA_PIF_1_MAX_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_AREA_PIF_1_MAX_CORE_0_AREA_PIF_1_MAX_S (0)
#define ASSIST_DEBUG_CORE_0_AREA_PIF_1_MAX_CORE_0_AREA_PIF_1_MAX_V(v) (((v) << 0) & 0xFFFFFFFFU)

// core0 area pc status register
#define ASSIST_DEBUG_CORE_0_AREA_PC_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x30))
#define ASSIST_DEBUG_CORE_0_AREA_PC_CORE_0_AREA_PC_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_AREA_PC_CORE_0_AREA_PC_S (0)
#define ASSIST_DEBUG_CORE_0_AREA_PC_CORE_0_AREA_PC_V(v) (((v) << 0) & 0xFFFFFFFFU)

// core0 area sp status register
#define ASSIST_DEBUG_CORE_0_AREA_SP_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x34))
#define ASSIST_DEBUG_CORE_0_AREA_SP_CORE_0_AREA_SP_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_AREA_SP_CORE_0_AREA_SP_S (0)
#define ASSIST_DEBUG_CORE_0_AREA_SP_CORE_0_AREA_SP_V(v) (((v) << 0) & 0xFFFFFFFFU)

// stack min value
#define ASSIST_DEBUG_CORE_0_SP_MIN_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x38))
#define ASSIST_DEBUG_CORE_0_SP_MIN_CORE_0_SP_MIN_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_SP_MIN_CORE_0_SP_MIN_S (0)
#define ASSIST_DEBUG_CORE_0_SP_MIN_CORE_0_SP_MIN_V(v) (((v) << 0) & 0xFFFFFFFFU)

// stack max value
#define ASSIST_DEBUG_CORE_0_SP_MAX_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x3C))
#define ASSIST_DEBUG_CORE_0_SP_MAX_CORE_0_SP_MAX_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_SP_MAX_CORE_0_SP_MAX_S (0)
#define ASSIST_DEBUG_CORE_0_SP_MAX_CORE_0_SP_MAX_V(v) (((v) << 0) & 0xFFFFFFFFU)

// stack monitor pc status register
#define ASSIST_DEBUG_CORE_0_SP_PC_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x40))
#define ASSIST_DEBUG_CORE_0_SP_PC_CORE_0_SP_PC_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_SP_PC_CORE_0_SP_PC_S (0)
#define ASSIST_DEBUG_CORE_0_SP_PC_CORE_0_SP_PC_V(v) (((v) << 0) & 0xFFFFFFFFU)

// record enable configuration register
#define ASSIST_DEBUG_CORE_0_RCD_EN_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x44))
#define ASSIST_DEBUG_CORE_0_RCD_EN_CORE_0_RCD_RECORDEN_M (0x00000001U)
#define ASSIST_DEBUG_CORE_0_RCD_EN_CORE_0_RCD_RECORDEN_S (0)
#define ASSIST_DEBUG_CORE_0_RCD_EN_CORE_0_RCD_RECORDEN_V(v) (((v) << 0) & 0x00000001U)
#define ASSIST_DEBUG_CORE_0_RCD_EN_CORE_0_RCD_PDEBUGEN_M (0x00000002U)
#define ASSIST_DEBUG_CORE_0_RCD_EN_CORE_0_RCD_PDEBUGEN_S (1)
#define ASSIST_DEBUG_CORE_0_RCD_EN_CORE_0_RCD_PDEBUGEN_V(v) (((v) << 1) & 0x00000002U)

// record status regsiter
#define ASSIST_DEBUG_CORE_0_RCD_PDEBUGPC_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x48))
#define ASSIST_DEBUG_CORE_0_RCD_PDEBUGPC_CORE_0_RCD_PDEBUGPC_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_RCD_PDEBUGPC_CORE_0_RCD_PDEBUGPC_S (0)
#define ASSIST_DEBUG_CORE_0_RCD_PDEBUGPC_CORE_0_RCD_PDEBUGPC_V(v) (((v) << 0) & 0xFFFFFFFFU)

// record status regsiter
#define ASSIST_DEBUG_CORE_0_RCD_PDEBUGSP_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x4C))
#define ASSIST_DEBUG_CORE_0_RCD_PDEBUGSP_CORE_0_RCD_PDEBUGSP_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_RCD_PDEBUGSP_CORE_0_RCD_PDEBUGSP_S (0)
#define ASSIST_DEBUG_CORE_0_RCD_PDEBUGSP_CORE_0_RCD_PDEBUGSP_V(v) (((v) << 0) & 0xFFFFFFFFU)

// exception monitor status register0
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_0_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x50))
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_0_CORE_0_IRAM0_RECORDING_ADDR_0_M (0x00FFFFFFU)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_0_CORE_0_IRAM0_RECORDING_ADDR_0_S (0)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_0_CORE_0_IRAM0_RECORDING_ADDR_0_V(v) (((v) << 0) & 0x00FFFFFFU)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_0_CORE_0_IRAM0_RECORDING_WR_0_M (0x01000000U)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_0_CORE_0_IRAM0_RECORDING_WR_0_S (24)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_0_CORE_0_IRAM0_RECORDING_WR_0_V(v) (((v) << 24) & 0x01000000U)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_0_CORE_0_IRAM0_RECORDING_LOADSTORE_0_M (0x02000000U)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_0_CORE_0_IRAM0_RECORDING_LOADSTORE_0_S (25)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_0_CORE_0_IRAM0_RECORDING_LOADSTORE_0_V(v) (((v) << 25) & 0x02000000U)

// exception monitor status register1
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_1_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x54))
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_1_CORE_0_IRAM0_RECORDING_ADDR_1_M (0x00FFFFFFU)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_1_CORE_0_IRAM0_RECORDING_ADDR_1_S (0)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_1_CORE_0_IRAM0_RECORDING_ADDR_1_V(v) (((v) << 0) & 0x00FFFFFFU)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_1_CORE_0_IRAM0_RECORDING_WR_1_M (0x01000000U)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_1_CORE_0_IRAM0_RECORDING_WR_1_S (24)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_1_CORE_0_IRAM0_RECORDING_WR_1_V(v) (((v) << 24) & 0x01000000U)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_1_CORE_0_IRAM0_RECORDING_LOADSTORE_1_M (0x02000000U)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_1_CORE_0_IRAM0_RECORDING_LOADSTORE_1_S (25)
#define ASSIST_DEBUG_CORE_0_IRAM0_EXCEPTION_MONITOR_1_CORE_0_IRAM0_RECORDING_LOADSTORE_1_V(v) (((v) << 25) & 0x02000000U)

// exception monitor status register2
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_0_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x58))
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_0_CORE_0_DRAM0_RECORDING_ADDR_0_M (0x00FFFFFFU)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_0_CORE_0_DRAM0_RECORDING_ADDR_0_S (0)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_0_CORE_0_DRAM0_RECORDING_ADDR_0_V(v) (((v) << 0) & 0x00FFFFFFU)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_0_CORE_0_DRAM0_RECORDING_WR_0_M (0x01000000U)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_0_CORE_0_DRAM0_RECORDING_WR_0_S (24)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_0_CORE_0_DRAM0_RECORDING_WR_0_V(v) (((v) << 24) & 0x01000000U)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_0_CORE_0_DRAM0_RECORDING_BYTEEN_0_M (0x1E000000U)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_0_CORE_0_DRAM0_RECORDING_BYTEEN_0_S (25)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_0_CORE_0_DRAM0_RECORDING_BYTEEN_0_V(v) (((v) << 25) & 0x1E000000U)

// exception monitor status register3
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_1_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x5C))
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_1_CORE_0_DRAM0_RECORDING_PC_0_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_1_CORE_0_DRAM0_RECORDING_PC_0_S (0)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_1_CORE_0_DRAM0_RECORDING_PC_0_V(v) (((v) << 0) & 0xFFFFFFFFU)

// exception monitor status register4
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_2_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x60))
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_2_CORE_0_DRAM0_RECORDING_ADDR_1_M (0x00FFFFFFU)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_2_CORE_0_DRAM0_RECORDING_ADDR_1_S (0)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_2_CORE_0_DRAM0_RECORDING_ADDR_1_V(v) (((v) << 0) & 0x00FFFFFFU)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_2_CORE_0_DRAM0_RECORDING_WR_1_M (0x01000000U)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_2_CORE_0_DRAM0_RECORDING_WR_1_S (24)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_2_CORE_0_DRAM0_RECORDING_WR_1_V(v) (((v) << 24) & 0x01000000U)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_2_CORE_0_DRAM0_RECORDING_BYTEEN_1_M (0x1E000000U)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_2_CORE_0_DRAM0_RECORDING_BYTEEN_1_S (25)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_2_CORE_0_DRAM0_RECORDING_BYTEEN_1_V(v) (((v) << 25) & 0x1E000000U)

// exception monitor status register5
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_3_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x64))
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_3_CORE_0_DRAM0_RECORDING_PC_1_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_3_CORE_0_DRAM0_RECORDING_PC_1_S (0)
#define ASSIST_DEBUG_CORE_0_DRAM0_EXCEPTION_MONITOR_3_CORE_0_DRAM0_RECORDING_PC_1_V(v) (((v) << 0) & 0xFFFFFFFFU)

// exception monitor status register6
#define ASSIST_DEBUG_CORE_X_IRAM0_DRAM0_EXCEPTION_MONITOR_0_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x68))
#define ASSIST_DEBUG_CORE_X_IRAM0_DRAM0_EXCEPTION_MONITOR_0_CORE_X_IRAM0_DRAM0_LIMIT_CYCLE_0_M (0x000FFFFFU)
#define ASSIST_DEBUG_CORE_X_IRAM0_DRAM0_EXCEPTION_MONITOR_0_CORE_X_IRAM0_DRAM0_LIMIT_CYCLE_0_S (0)
#define ASSIST_DEBUG_CORE_X_IRAM0_DRAM0_EXCEPTION_MONITOR_0_CORE_X_IRAM0_DRAM0_LIMIT_CYCLE_0_V(v) (((v) << 0) & 0x000FFFFFU)

// exception monitor status register7
#define ASSIST_DEBUG_CORE_X_IRAM0_DRAM0_EXCEPTION_MONITOR_1_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x6C))
#define ASSIST_DEBUG_CORE_X_IRAM0_DRAM0_EXCEPTION_MONITOR_1_CORE_X_IRAM0_DRAM0_LIMIT_CYCLE_1_M (0x000FFFFFU)
#define ASSIST_DEBUG_CORE_X_IRAM0_DRAM0_EXCEPTION_MONITOR_1_CORE_X_IRAM0_DRAM0_LIMIT_CYCLE_1_S (0)
#define ASSIST_DEBUG_CORE_X_IRAM0_DRAM0_EXCEPTION_MONITOR_1_CORE_X_IRAM0_DRAM0_LIMIT_CYCLE_1_V(v) (((v) << 0) & 0x000FFFFFU)

// cpu status register
#define ASSIST_DEBUG_C0RE_0_LASTPC_BEFORE_EXCEPTION_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x70))
#define ASSIST_DEBUG_C0RE_0_LASTPC_BEFORE_EXCEPTION_CORE_0_LASTPC_BEFORE_EXC_M (0xFFFFFFFFU)
#define ASSIST_DEBUG_C0RE_0_LASTPC_BEFORE_EXCEPTION_CORE_0_LASTPC_BEFORE_EXC_S (0)
#define ASSIST_DEBUG_C0RE_0_LASTPC_BEFORE_EXCEPTION_CORE_0_LASTPC_BEFORE_EXC_V(v) (((v) << 0) & 0xFFFFFFFFU)

// cpu status register
#define ASSIST_DEBUG_C0RE_0_DEBUG_MODE_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x74))
#define ASSIST_DEBUG_C0RE_0_DEBUG_MODE_CORE_0_DEBUG_MODE_M (0x00000001U)
#define ASSIST_DEBUG_C0RE_0_DEBUG_MODE_CORE_0_DEBUG_MODE_S (0)
#define ASSIST_DEBUG_C0RE_0_DEBUG_MODE_CORE_0_DEBUG_MODE_V(v) (((v) << 0) & 0x00000001U)
#define ASSIST_DEBUG_C0RE_0_DEBUG_MODE_CORE_0_DEBUG_MODULE_ACTIVE_M (0x00000002U)
#define ASSIST_DEBUG_C0RE_0_DEBUG_MODE_CORE_0_DEBUG_MODULE_ACTIVE_S (1)
#define ASSIST_DEBUG_C0RE_0_DEBUG_MODE_CORE_0_DEBUG_MODULE_ACTIVE_V(v) (((v) << 1) & 0x00000002U)

// clock register
#define ASSIST_DEBUG_CLOCK_GATE_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x78))
#define ASSIST_DEBUG_CLOCK_GATE_CLK_EN_M (0x00000001U)
#define ASSIST_DEBUG_CLOCK_GATE_CLK_EN_S (0)
#define ASSIST_DEBUG_CLOCK_GATE_CLK_EN_V(v) (((v) << 0) & 0x00000001U)

// version register
#define ASSIST_DEBUG_DATE_REG ((volatile uint32_t *)(ASSIST_DEBUG_BASE + 0x3FC))
#define ASSIST_DEBUG_DATE_ASSIST_DEBUG_DATE_M (0x0FFFFFFFU)
#define ASSIST_DEBUG_DATE_ASSIST_DEBUG_DATE_S (0)
#define ASSIST_DEBUG_DATE_ASSIST_DEBUG_DATE_V(v) (((v) << 0) & 0x0FFFFFFFU)

#endif // ASSIST_DEBUG_H
