/*
 * HP_SYS.h
 * High-Power System
 * Base Address: 0x60095000
 */

#ifndef HP_SYS_H
#define HP_SYS_H

#include <stdint.h>

#define HP_SYS_BASE 0x60095000

// EXTERNAL DEVICE ENCRYPTION/DECRYPTION configuration register
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x0))
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_ENABLE_SPI_MANUAL_ENCRYPT_M (0x00000001U)
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_ENABLE_SPI_MANUAL_ENCRYPT_S (0)
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_ENABLE_SPI_MANUAL_ENCRYPT_V(v) (((v) << 0) & 0x00000001U)
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_ENABLE_DOWNLOAD_DB_ENCRYPT_M (0x00000002U)
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_ENABLE_DOWNLOAD_DB_ENCRYPT_S (1)
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_ENABLE_DOWNLOAD_DB_ENCRYPT_V(v) (((v) << 1) & 0x00000002U)
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_ENABLE_DOWNLOAD_G0CB_DECRYPT_M (0x00000004U)
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_ENABLE_DOWNLOAD_G0CB_DECRYPT_S (2)
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_ENABLE_DOWNLOAD_G0CB_DECRYPT_V(v) (((v) << 2) & 0x00000004U)
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_ENABLE_DOWNLOAD_MANUAL_ENCRYPT_M (0x00000008U)
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_ENABLE_DOWNLOAD_MANUAL_ENCRYPT_S (3)
#define HP_SYS_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_ENABLE_DOWNLOAD_MANUAL_ENCRYPT_V(v) (((v) << 3) & 0x00000008U)

// HP memory usage configuration register
#define HP_SYS_SRAM_USAGE_CONF_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x4))
#define HP_SYS_SRAM_USAGE_CONF_CACHE_USAGE_M (0x00000001U)
#define HP_SYS_SRAM_USAGE_CONF_CACHE_USAGE_S (0)
#define HP_SYS_SRAM_USAGE_CONF_CACHE_USAGE_V(v) (((v) << 0) & 0x00000001U)
#define HP_SYS_SRAM_USAGE_CONF_SRAM_USAGE_M (0x00000F00U)
#define HP_SYS_SRAM_USAGE_CONF_SRAM_USAGE_S (8)
#define HP_SYS_SRAM_USAGE_CONF_SRAM_USAGE_V(v) (((v) << 8) & 0x00000F00U)
#define HP_SYS_SRAM_USAGE_CONF_MAC_DUMP_ALLOC_M (0x00010000U)
#define HP_SYS_SRAM_USAGE_CONF_MAC_DUMP_ALLOC_S (16)
#define HP_SYS_SRAM_USAGE_CONF_MAC_DUMP_ALLOC_V(v) (((v) << 16) & 0x00010000U)

// HP anti-DPA security configuration register
#define HP_SYS_SEC_DPA_CONF_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x8))
#define HP_SYS_SEC_DPA_CONF_SEC_DPA_LEVEL_M (0x00000003U)
#define HP_SYS_SEC_DPA_CONF_SEC_DPA_LEVEL_S (0)
#define HP_SYS_SEC_DPA_CONF_SEC_DPA_LEVEL_V(v) (((v) << 0) & 0x00000003U)
#define HP_SYS_SEC_DPA_CONF_SEC_DPA_CFG_SEL_M (0x00000004U)
#define HP_SYS_SEC_DPA_CONF_SEC_DPA_CFG_SEL_S (2)
#define HP_SYS_SEC_DPA_CONF_SEC_DPA_CFG_SEL_V(v) (((v) << 2) & 0x00000004U)

// CPU_PERI_TIMEOUT configuration register
#define HP_SYS_CPU_PERI_TIMEOUT_CONF_REG ((volatile uint32_t *)(HP_SYS_BASE + 0xC))
#define HP_SYS_CPU_PERI_TIMEOUT_CONF_CPU_PERI_TIMEOUT_THRES_M (0x0000FFFFU)
#define HP_SYS_CPU_PERI_TIMEOUT_CONF_CPU_PERI_TIMEOUT_THRES_S (0)
#define HP_SYS_CPU_PERI_TIMEOUT_CONF_CPU_PERI_TIMEOUT_THRES_V(v) (((v) << 0) & 0x0000FFFFU)
#define HP_SYS_CPU_PERI_TIMEOUT_CONF_CPU_PERI_TIMEOUT_INT_CLEAR_M (0x00010000U)
#define HP_SYS_CPU_PERI_TIMEOUT_CONF_CPU_PERI_TIMEOUT_INT_CLEAR_S (16)
#define HP_SYS_CPU_PERI_TIMEOUT_CONF_CPU_PERI_TIMEOUT_INT_CLEAR_V(v) (((v) << 16) & 0x00010000U)
#define HP_SYS_CPU_PERI_TIMEOUT_CONF_CPU_PERI_TIMEOUT_PROTECT_EN_M (0x00020000U)
#define HP_SYS_CPU_PERI_TIMEOUT_CONF_CPU_PERI_TIMEOUT_PROTECT_EN_S (17)
#define HP_SYS_CPU_PERI_TIMEOUT_CONF_CPU_PERI_TIMEOUT_PROTECT_EN_V(v) (((v) << 17) & 0x00020000U)

// CPU_PERI_TIMEOUT_ADDR register
#define HP_SYS_CPU_PERI_TIMEOUT_ADDR_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x10))
#define HP_SYS_CPU_PERI_TIMEOUT_ADDR_CPU_PERI_TIMEOUT_ADDR_M (0xFFFFFFFFU)
#define HP_SYS_CPU_PERI_TIMEOUT_ADDR_CPU_PERI_TIMEOUT_ADDR_S (0)
#define HP_SYS_CPU_PERI_TIMEOUT_ADDR_CPU_PERI_TIMEOUT_ADDR_V(v) (((v) << 0) & 0xFFFFFFFFU)

// CPU_PERI_TIMEOUT_UID register
#define HP_SYS_CPU_PERI_TIMEOUT_UID_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x14))
#define HP_SYS_CPU_PERI_TIMEOUT_UID_CPU_PERI_TIMEOUT_UID_M (0x0000007FU)
#define HP_SYS_CPU_PERI_TIMEOUT_UID_CPU_PERI_TIMEOUT_UID_S (0)
#define HP_SYS_CPU_PERI_TIMEOUT_UID_CPU_PERI_TIMEOUT_UID_V(v) (((v) << 0) & 0x0000007FU)

// HP_PERI_TIMEOUT configuration register
#define HP_SYS_HP_PERI_TIMEOUT_CONF_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x18))
#define HP_SYS_HP_PERI_TIMEOUT_CONF_HP_PERI_TIMEOUT_THRES_M (0x0000FFFFU)
#define HP_SYS_HP_PERI_TIMEOUT_CONF_HP_PERI_TIMEOUT_THRES_S (0)
#define HP_SYS_HP_PERI_TIMEOUT_CONF_HP_PERI_TIMEOUT_THRES_V(v) (((v) << 0) & 0x0000FFFFU)
#define HP_SYS_HP_PERI_TIMEOUT_CONF_HP_PERI_TIMEOUT_INT_CLEAR_M (0x00010000U)
#define HP_SYS_HP_PERI_TIMEOUT_CONF_HP_PERI_TIMEOUT_INT_CLEAR_S (16)
#define HP_SYS_HP_PERI_TIMEOUT_CONF_HP_PERI_TIMEOUT_INT_CLEAR_V(v) (((v) << 16) & 0x00010000U)
#define HP_SYS_HP_PERI_TIMEOUT_CONF_HP_PERI_TIMEOUT_PROTECT_EN_M (0x00020000U)
#define HP_SYS_HP_PERI_TIMEOUT_CONF_HP_PERI_TIMEOUT_PROTECT_EN_S (17)
#define HP_SYS_HP_PERI_TIMEOUT_CONF_HP_PERI_TIMEOUT_PROTECT_EN_V(v) (((v) << 17) & 0x00020000U)

// HP_PERI_TIMEOUT_ADDR register
#define HP_SYS_HP_PERI_TIMEOUT_ADDR_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x1C))
#define HP_SYS_HP_PERI_TIMEOUT_ADDR_HP_PERI_TIMEOUT_ADDR_M (0xFFFFFFFFU)
#define HP_SYS_HP_PERI_TIMEOUT_ADDR_HP_PERI_TIMEOUT_ADDR_S (0)
#define HP_SYS_HP_PERI_TIMEOUT_ADDR_HP_PERI_TIMEOUT_ADDR_V(v) (((v) << 0) & 0xFFFFFFFFU)

// HP_PERI_TIMEOUT_UID register
#define HP_SYS_HP_PERI_TIMEOUT_UID_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x20))
#define HP_SYS_HP_PERI_TIMEOUT_UID_HP_PERI_TIMEOUT_UID_M (0x0000007FU)
#define HP_SYS_HP_PERI_TIMEOUT_UID_HP_PERI_TIMEOUT_UID_S (0)
#define HP_SYS_HP_PERI_TIMEOUT_UID_HP_PERI_TIMEOUT_UID_V(v) (((v) << 0) & 0x0000007FU)

// MODEM_PERI_TIMEOUT configuration register
#define HP_SYS_MODEM_PERI_TIMEOUT_CONF_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x24))
#define HP_SYS_MODEM_PERI_TIMEOUT_CONF_MODEM_PERI_TIMEOUT_THRES_M (0x0000FFFFU)
#define HP_SYS_MODEM_PERI_TIMEOUT_CONF_MODEM_PERI_TIMEOUT_THRES_S (0)
#define HP_SYS_MODEM_PERI_TIMEOUT_CONF_MODEM_PERI_TIMEOUT_THRES_V(v) (((v) << 0) & 0x0000FFFFU)
#define HP_SYS_MODEM_PERI_TIMEOUT_CONF_MODEM_PERI_TIMEOUT_INT_CLEAR_M (0x00010000U)
#define HP_SYS_MODEM_PERI_TIMEOUT_CONF_MODEM_PERI_TIMEOUT_INT_CLEAR_S (16)
#define HP_SYS_MODEM_PERI_TIMEOUT_CONF_MODEM_PERI_TIMEOUT_INT_CLEAR_V(v) (((v) << 16) & 0x00010000U)
#define HP_SYS_MODEM_PERI_TIMEOUT_CONF_MODEM_PERI_TIMEOUT_PROTECT_EN_M (0x00020000U)
#define HP_SYS_MODEM_PERI_TIMEOUT_CONF_MODEM_PERI_TIMEOUT_PROTECT_EN_S (17)
#define HP_SYS_MODEM_PERI_TIMEOUT_CONF_MODEM_PERI_TIMEOUT_PROTECT_EN_V(v) (((v) << 17) & 0x00020000U)

// MODEM_PERI_TIMEOUT_ADDR register
#define HP_SYS_MODEM_PERI_TIMEOUT_ADDR_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x28))
#define HP_SYS_MODEM_PERI_TIMEOUT_ADDR_MODEM_PERI_TIMEOUT_ADDR_M (0xFFFFFFFFU)
#define HP_SYS_MODEM_PERI_TIMEOUT_ADDR_MODEM_PERI_TIMEOUT_ADDR_S (0)
#define HP_SYS_MODEM_PERI_TIMEOUT_ADDR_MODEM_PERI_TIMEOUT_ADDR_V(v) (((v) << 0) & 0xFFFFFFFFU)

// MODEM_PERI_TIMEOUT_UID register
#define HP_SYS_MODEM_PERI_TIMEOUT_UID_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x2C))
#define HP_SYS_MODEM_PERI_TIMEOUT_UID_MODEM_PERI_TIMEOUT_UID_M (0x0000007FU)
#define HP_SYS_MODEM_PERI_TIMEOUT_UID_MODEM_PERI_TIMEOUT_UID_S (0)
#define HP_SYS_MODEM_PERI_TIMEOUT_UID_MODEM_PERI_TIMEOUT_UID_V(v) (((v) << 0) & 0x0000007FU)

// SDIO Control configuration register
#define HP_SYS_SDIO_CTRL_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x30))
#define HP_SYS_SDIO_CTRL_DIS_SDIO_PROB_M (0x00000001U)
#define HP_SYS_SDIO_CTRL_DIS_SDIO_PROB_S (0)
#define HP_SYS_SDIO_CTRL_DIS_SDIO_PROB_V(v) (((v) << 0) & 0x00000001U)
#define HP_SYS_SDIO_CTRL_SDIO_WIN_ACCESS_EN_M (0x00000002U)
#define HP_SYS_SDIO_CTRL_SDIO_WIN_ACCESS_EN_S (1)
#define HP_SYS_SDIO_CTRL_SDIO_WIN_ACCESS_EN_V(v) (((v) << 1) & 0x00000002U)

// Retention configuration register
#define HP_SYS_RETENTION_CONF_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x34))
#define HP_SYS_RETENTION_CONF_RETENTION_DISABLE_M (0x00000001U)
#define HP_SYS_RETENTION_CONF_RETENTION_DISABLE_S (0)
#define HP_SYS_RETENTION_CONF_RETENTION_DISABLE_V(v) (((v) << 0) & 0x00000001U)

// Rom-Table lock register
#define HP_SYS_ROM_TABLE_LOCK_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x38))
#define HP_SYS_ROM_TABLE_LOCK_ROM_TABLE_LOCK_M (0x00000001U)
#define HP_SYS_ROM_TABLE_LOCK_ROM_TABLE_LOCK_S (0)
#define HP_SYS_ROM_TABLE_LOCK_ROM_TABLE_LOCK_V(v) (((v) << 0) & 0x00000001U)

// Rom-Table register
#define HP_SYS_ROM_TABLE_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x3C))
#define HP_SYS_ROM_TABLE_ROM_TABLE_M (0xFFFFFFFFU)
#define HP_SYS_ROM_TABLE_ROM_TABLE_S (0)
#define HP_SYS_ROM_TABLE_ROM_TABLE_V(v) (((v) << 0) & 0xFFFFFFFFU)

// Core Debug runstall configure register
#define HP_SYS_CORE_DEBUG_RUNSTALL_CONF_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x40))
#define HP_SYS_CORE_DEBUG_RUNSTALL_CONF_CORE_DEBUG_RUNSTALL_ENABLE_M (0x00000001U)
#define HP_SYS_CORE_DEBUG_RUNSTALL_CONF_CORE_DEBUG_RUNSTALL_ENABLE_S (0)
#define HP_SYS_CORE_DEBUG_RUNSTALL_CONF_CORE_DEBUG_RUNSTALL_ENABLE_V(v) (((v) << 0) & 0x00000001U)

// MEM_TEST configuration register
#define HP_SYS_MEM_TEST_CONF_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x44))
#define HP_SYS_MEM_TEST_CONF_HP_MEM_WPULSE_M (0x00000007U)
#define HP_SYS_MEM_TEST_CONF_HP_MEM_WPULSE_S (0)
#define HP_SYS_MEM_TEST_CONF_HP_MEM_WPULSE_V(v) (((v) << 0) & 0x00000007U)
#define HP_SYS_MEM_TEST_CONF_HP_MEM_WA_M (0x00000038U)
#define HP_SYS_MEM_TEST_CONF_HP_MEM_WA_S (3)
#define HP_SYS_MEM_TEST_CONF_HP_MEM_WA_V(v) (((v) << 3) & 0x00000038U)
#define HP_SYS_MEM_TEST_CONF_HP_MEM_RA_M (0x000000C0U)
#define HP_SYS_MEM_TEST_CONF_HP_MEM_RA_S (6)
#define HP_SYS_MEM_TEST_CONF_HP_MEM_RA_V(v) (((v) << 6) & 0x000000C0U)

// redcy eco register.
#define HP_SYS_RND_ECO_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x3E0))
#define HP_SYS_RND_ECO_REDCY_ENA_M (0x00000001U)
#define HP_SYS_RND_ECO_REDCY_ENA_S (0)
#define HP_SYS_RND_ECO_REDCY_ENA_V(v) (((v) << 0) & 0x00000001U)
#define HP_SYS_RND_ECO_REDCY_RESULT_M (0x00000002U)
#define HP_SYS_RND_ECO_REDCY_RESULT_S (1)
#define HP_SYS_RND_ECO_REDCY_RESULT_V(v) (((v) << 1) & 0x00000002U)

// redcy eco low register.
#define HP_SYS_RND_ECO_LOW_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x3E4))
#define HP_SYS_RND_ECO_LOW_REDCY_LOW_M (0xFFFFFFFFU)
#define HP_SYS_RND_ECO_LOW_REDCY_LOW_S (0)
#define HP_SYS_RND_ECO_LOW_REDCY_LOW_V(v) (((v) << 0) & 0xFFFFFFFFU)

// redcy eco high register.
#define HP_SYS_RND_ECO_HIGH_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x3E8))
#define HP_SYS_RND_ECO_HIGH_REDCY_HIGH_M (0xFFFFFFFFU)
#define HP_SYS_RND_ECO_HIGH_REDCY_HIGH_S (0)
#define HP_SYS_RND_ECO_HIGH_REDCY_HIGH_V(v) (((v) << 0) & 0xFFFFFFFFU)

// HP-SYSTEM clock gating configure register
#define HP_SYS_CLOCK_GATE_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x3F8))
#define HP_SYS_CLOCK_GATE_CLK_EN_M (0x00000001U)
#define HP_SYS_CLOCK_GATE_CLK_EN_S (0)
#define HP_SYS_CLOCK_GATE_CLK_EN_V(v) (((v) << 0) & 0x00000001U)

// Date register.
#define HP_SYS_DATE_REG ((volatile uint32_t *)(HP_SYS_BASE + 0x3FC))
#define HP_SYS_DATE_DATE_M (0x0FFFFFFFU)
#define HP_SYS_DATE_DATE_S (0)
#define HP_SYS_DATE_DATE_V(v) (((v) << 0) & 0x0FFFFFFFU)

#endif // HP_SYS_H
