/*
 * INTERRUPT_CORE0.h
 * Interrupt Controller (Core 0)
 * Base Address: 0x60010000
 */

#ifndef INTERRUPT_CORE0_H
#define INTERRUPT_CORE0_H

#include <stdint.h>

#define INTERRUPT_CORE0_BASE 0x60010000

// register description
#define INTERRUPT_CORE0_WIFI_MAC_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x0))
#define INTERRUPT_CORE0_WIFI_MAC_INTR_MAP_WIFI_MAC_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_WIFI_MAC_INTR_MAP_WIFI_MAC_INTR_MAP_S (0)
#define INTERRUPT_CORE0_WIFI_MAC_INTR_MAP_WIFI_MAC_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_WIFI_MAC_NMI_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x4))
#define INTERRUPT_CORE0_WIFI_MAC_NMI_MAP_WIFI_MAC_NMI_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_WIFI_MAC_NMI_MAP_WIFI_MAC_NMI_MAP_S (0)
#define INTERRUPT_CORE0_WIFI_MAC_NMI_MAP_WIFI_MAC_NMI_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_WIFI_PWR_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x8))
#define INTERRUPT_CORE0_WIFI_PWR_INTR_MAP_WIFI_PWR_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_WIFI_PWR_INTR_MAP_WIFI_PWR_INTR_MAP_S (0)
#define INTERRUPT_CORE0_WIFI_PWR_INTR_MAP_WIFI_PWR_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_WIFI_BB_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xC))
#define INTERRUPT_CORE0_WIFI_BB_INTR_MAP_WIFI_BB_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_WIFI_BB_INTR_MAP_WIFI_BB_INTR_MAP_S (0)
#define INTERRUPT_CORE0_WIFI_BB_INTR_MAP_WIFI_BB_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_BT_MAC_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x10))
#define INTERRUPT_CORE0_BT_MAC_INTR_MAP_BT_MAC_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_BT_MAC_INTR_MAP_BT_MAC_INTR_MAP_S (0)
#define INTERRUPT_CORE0_BT_MAC_INTR_MAP_BT_MAC_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_BT_BB_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x14))
#define INTERRUPT_CORE0_BT_BB_INTR_MAP_BT_BB_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_BT_BB_INTR_MAP_BT_BB_INTR_MAP_S (0)
#define INTERRUPT_CORE0_BT_BB_INTR_MAP_BT_BB_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_BT_BB_NMI_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x18))
#define INTERRUPT_CORE0_BT_BB_NMI_MAP_BT_BB_NMI_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_BT_BB_NMI_MAP_BT_BB_NMI_MAP_S (0)
#define INTERRUPT_CORE0_BT_BB_NMI_MAP_BT_BB_NMI_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_LP_TIMER_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x1C))
#define INTERRUPT_CORE0_LP_TIMER_INTR_MAP_LP_TIMER_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_LP_TIMER_INTR_MAP_LP_TIMER_INTR_MAP_S (0)
#define INTERRUPT_CORE0_LP_TIMER_INTR_MAP_LP_TIMER_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_COEX_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x20))
#define INTERRUPT_CORE0_COEX_INTR_MAP_COEX_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_COEX_INTR_MAP_COEX_INTR_MAP_S (0)
#define INTERRUPT_CORE0_COEX_INTR_MAP_COEX_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_BLE_TIMER_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x24))
#define INTERRUPT_CORE0_BLE_TIMER_INTR_MAP_BLE_TIMER_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_BLE_TIMER_INTR_MAP_BLE_TIMER_INTR_MAP_S (0)
#define INTERRUPT_CORE0_BLE_TIMER_INTR_MAP_BLE_TIMER_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_BLE_SEC_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x28))
#define INTERRUPT_CORE0_BLE_SEC_INTR_MAP_BLE_SEC_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_BLE_SEC_INTR_MAP_BLE_SEC_INTR_MAP_S (0)
#define INTERRUPT_CORE0_BLE_SEC_INTR_MAP_BLE_SEC_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_I2C_MST_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x2C))
#define INTERRUPT_CORE0_I2C_MST_INTR_MAP_I2C_MST_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_I2C_MST_INTR_MAP_I2C_MST_INTR_MAP_S (0)
#define INTERRUPT_CORE0_I2C_MST_INTR_MAP_I2C_MST_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_ZB_MAC_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x30))
#define INTERRUPT_CORE0_ZB_MAC_INTR_MAP_ZB_MAC_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_ZB_MAC_INTR_MAP_ZB_MAC_INTR_MAP_S (0)
#define INTERRUPT_CORE0_ZB_MAC_INTR_MAP_ZB_MAC_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_PMU_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x34))
#define INTERRUPT_CORE0_PMU_INTR_MAP_PMU_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_PMU_INTR_MAP_PMU_INTR_MAP_S (0)
#define INTERRUPT_CORE0_PMU_INTR_MAP_PMU_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_EFUSE_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x38))
#define INTERRUPT_CORE0_EFUSE_INTR_MAP_EFUSE_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_EFUSE_INTR_MAP_EFUSE_INTR_MAP_S (0)
#define INTERRUPT_CORE0_EFUSE_INTR_MAP_EFUSE_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_LP_RTC_TIMER_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x3C))
#define INTERRUPT_CORE0_LP_RTC_TIMER_INTR_MAP_LP_RTC_TIMER_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_LP_RTC_TIMER_INTR_MAP_LP_RTC_TIMER_INTR_MAP_S (0)
#define INTERRUPT_CORE0_LP_RTC_TIMER_INTR_MAP_LP_RTC_TIMER_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_LP_UART_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x40))
#define INTERRUPT_CORE0_LP_UART_INTR_MAP_LP_UART_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_LP_UART_INTR_MAP_LP_UART_INTR_MAP_S (0)
#define INTERRUPT_CORE0_LP_UART_INTR_MAP_LP_UART_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_LP_I2C_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x44))
#define INTERRUPT_CORE0_LP_I2C_INTR_MAP_LP_I2C_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_LP_I2C_INTR_MAP_LP_I2C_INTR_MAP_S (0)
#define INTERRUPT_CORE0_LP_I2C_INTR_MAP_LP_I2C_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_LP_WDT_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x48))
#define INTERRUPT_CORE0_LP_WDT_INTR_MAP_LP_WDT_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_LP_WDT_INTR_MAP_LP_WDT_INTR_MAP_S (0)
#define INTERRUPT_CORE0_LP_WDT_INTR_MAP_LP_WDT_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_LP_PERI_TIMEOUT_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x4C))
#define INTERRUPT_CORE0_LP_PERI_TIMEOUT_INTR_MAP_LP_PERI_TIMEOUT_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_LP_PERI_TIMEOUT_INTR_MAP_LP_PERI_TIMEOUT_INTR_MAP_S (0)
#define INTERRUPT_CORE0_LP_PERI_TIMEOUT_INTR_MAP_LP_PERI_TIMEOUT_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_LP_APM_M0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x50))
#define INTERRUPT_CORE0_LP_APM_M0_INTR_MAP_LP_APM_M0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_LP_APM_M0_INTR_MAP_LP_APM_M0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_LP_APM_M0_INTR_MAP_LP_APM_M0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_LP_APM_M1_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x54))
#define INTERRUPT_CORE0_LP_APM_M1_INTR_MAP_LP_APM_M1_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_LP_APM_M1_INTR_MAP_LP_APM_M1_INTR_MAP_S (0)
#define INTERRUPT_CORE0_LP_APM_M1_INTR_MAP_LP_APM_M1_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_0_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x58))
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_0_MAP_CPU_INTR_FROM_CPU_0_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_0_MAP_CPU_INTR_FROM_CPU_0_MAP_S (0)
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_0_MAP_CPU_INTR_FROM_CPU_0_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_1_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x5C))
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_1_MAP_CPU_INTR_FROM_CPU_1_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_1_MAP_CPU_INTR_FROM_CPU_1_MAP_S (0)
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_1_MAP_CPU_INTR_FROM_CPU_1_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_2_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x60))
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_2_MAP_CPU_INTR_FROM_CPU_2_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_2_MAP_CPU_INTR_FROM_CPU_2_MAP_S (0)
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_2_MAP_CPU_INTR_FROM_CPU_2_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_3_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x64))
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_3_MAP_CPU_INTR_FROM_CPU_3_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_3_MAP_CPU_INTR_FROM_CPU_3_MAP_S (0)
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_3_MAP_CPU_INTR_FROM_CPU_3_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_ASSIST_DEBUG_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x68))
#define INTERRUPT_CORE0_ASSIST_DEBUG_INTR_MAP_ASSIST_DEBUG_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_ASSIST_DEBUG_INTR_MAP_ASSIST_DEBUG_INTR_MAP_S (0)
#define INTERRUPT_CORE0_ASSIST_DEBUG_INTR_MAP_ASSIST_DEBUG_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_TRACE_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x6C))
#define INTERRUPT_CORE0_TRACE_INTR_MAP_TRACE_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_TRACE_INTR_MAP_TRACE_INTR_MAP_S (0)
#define INTERRUPT_CORE0_TRACE_INTR_MAP_TRACE_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_CACHE_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x70))
#define INTERRUPT_CORE0_CACHE_INTR_MAP_CACHE_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_CACHE_INTR_MAP_CACHE_INTR_MAP_S (0)
#define INTERRUPT_CORE0_CACHE_INTR_MAP_CACHE_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_CPU_PERI_TIMEOUT_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x74))
#define INTERRUPT_CORE0_CPU_PERI_TIMEOUT_INTR_MAP_CPU_PERI_TIMEOUT_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_CPU_PERI_TIMEOUT_INTR_MAP_CPU_PERI_TIMEOUT_INTR_MAP_S (0)
#define INTERRUPT_CORE0_CPU_PERI_TIMEOUT_INTR_MAP_CPU_PERI_TIMEOUT_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x78))
#define INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_MAP_GPIO_INTERRUPT_PRO_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_MAP_GPIO_INTERRUPT_PRO_MAP_S (0)
#define INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_MAP_GPIO_INTERRUPT_PRO_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_NMI_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x7C))
#define INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_NMI_MAP_GPIO_INTERRUPT_PRO_NMI_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_NMI_MAP_GPIO_INTERRUPT_PRO_NMI_MAP_S (0)
#define INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_NMI_MAP_GPIO_INTERRUPT_PRO_NMI_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_PAU_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x80))
#define INTERRUPT_CORE0_PAU_INTR_MAP_PAU_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_PAU_INTR_MAP_PAU_INTR_MAP_S (0)
#define INTERRUPT_CORE0_PAU_INTR_MAP_PAU_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_HP_PERI_TIMEOUT_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x84))
#define INTERRUPT_CORE0_HP_PERI_TIMEOUT_INTR_MAP_HP_PERI_TIMEOUT_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_HP_PERI_TIMEOUT_INTR_MAP_HP_PERI_TIMEOUT_INTR_MAP_S (0)
#define INTERRUPT_CORE0_HP_PERI_TIMEOUT_INTR_MAP_HP_PERI_TIMEOUT_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_MODEM_PERI_TIMEOUT_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x88))
#define INTERRUPT_CORE0_MODEM_PERI_TIMEOUT_INTR_MAP_MODEM_PERI_TIMEOUT_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_MODEM_PERI_TIMEOUT_INTR_MAP_MODEM_PERI_TIMEOUT_INTR_MAP_S (0)
#define INTERRUPT_CORE0_MODEM_PERI_TIMEOUT_INTR_MAP_MODEM_PERI_TIMEOUT_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_HP_APM_M0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x8C))
#define INTERRUPT_CORE0_HP_APM_M0_INTR_MAP_HP_APM_M0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_HP_APM_M0_INTR_MAP_HP_APM_M0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_HP_APM_M0_INTR_MAP_HP_APM_M0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_HP_APM_M1_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x90))
#define INTERRUPT_CORE0_HP_APM_M1_INTR_MAP_HP_APM_M1_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_HP_APM_M1_INTR_MAP_HP_APM_M1_INTR_MAP_S (0)
#define INTERRUPT_CORE0_HP_APM_M1_INTR_MAP_HP_APM_M1_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_HP_APM_M2_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x94))
#define INTERRUPT_CORE0_HP_APM_M2_INTR_MAP_HP_APM_M2_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_HP_APM_M2_INTR_MAP_HP_APM_M2_INTR_MAP_S (0)
#define INTERRUPT_CORE0_HP_APM_M2_INTR_MAP_HP_APM_M2_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_HP_APM_M3_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x98))
#define INTERRUPT_CORE0_HP_APM_M3_INTR_MAP_HP_APM_M3_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_HP_APM_M3_INTR_MAP_HP_APM_M3_INTR_MAP_S (0)
#define INTERRUPT_CORE0_HP_APM_M3_INTR_MAP_HP_APM_M3_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_LP_APM0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x9C))
#define INTERRUPT_CORE0_LP_APM0_INTR_MAP_LP_APM0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_LP_APM0_INTR_MAP_LP_APM0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_LP_APM0_INTR_MAP_LP_APM0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_MSPI_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xA0))
#define INTERRUPT_CORE0_MSPI_INTR_MAP_MSPI_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_MSPI_INTR_MAP_MSPI_INTR_MAP_S (0)
#define INTERRUPT_CORE0_MSPI_INTR_MAP_MSPI_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_I2S1_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xA4))
#define INTERRUPT_CORE0_I2S1_INTR_MAP_I2S1_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_I2S1_INTR_MAP_I2S1_INTR_MAP_S (0)
#define INTERRUPT_CORE0_I2S1_INTR_MAP_I2S1_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_UHCI0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xA8))
#define INTERRUPT_CORE0_UHCI0_INTR_MAP_UHCI0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_UHCI0_INTR_MAP_UHCI0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_UHCI0_INTR_MAP_UHCI0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_UART0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xAC))
#define INTERRUPT_CORE0_UART0_INTR_MAP_UART0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_UART0_INTR_MAP_UART0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_UART0_INTR_MAP_UART0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_UART1_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xB0))
#define INTERRUPT_CORE0_UART1_INTR_MAP_UART1_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_UART1_INTR_MAP_UART1_INTR_MAP_S (0)
#define INTERRUPT_CORE0_UART1_INTR_MAP_UART1_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_LEDC_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xB4))
#define INTERRUPT_CORE0_LEDC_INTR_MAP_LEDC_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_LEDC_INTR_MAP_LEDC_INTR_MAP_S (0)
#define INTERRUPT_CORE0_LEDC_INTR_MAP_LEDC_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_CAN0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xB8))
#define INTERRUPT_CORE0_CAN0_INTR_MAP_CAN0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_CAN0_INTR_MAP_CAN0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_CAN0_INTR_MAP_CAN0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_CAN1_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xBC))
#define INTERRUPT_CORE0_CAN1_INTR_MAP_CAN1_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_CAN1_INTR_MAP_CAN1_INTR_MAP_S (0)
#define INTERRUPT_CORE0_CAN1_INTR_MAP_CAN1_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_USB_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xC0))
#define INTERRUPT_CORE0_USB_INTR_MAP_USB_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_USB_INTR_MAP_USB_INTR_MAP_S (0)
#define INTERRUPT_CORE0_USB_INTR_MAP_USB_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_RMT_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xC4))
#define INTERRUPT_CORE0_RMT_INTR_MAP_RMT_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_RMT_INTR_MAP_RMT_INTR_MAP_S (0)
#define INTERRUPT_CORE0_RMT_INTR_MAP_RMT_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_I2C_EXT0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xC8))
#define INTERRUPT_CORE0_I2C_EXT0_INTR_MAP_I2C_EXT0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_I2C_EXT0_INTR_MAP_I2C_EXT0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_I2C_EXT0_INTR_MAP_I2C_EXT0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_TG0_T0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xCC))
#define INTERRUPT_CORE0_TG0_T0_INTR_MAP_TG0_T0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_TG0_T0_INTR_MAP_TG0_T0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_TG0_T0_INTR_MAP_TG0_T0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_TG0_T1_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xD0))
#define INTERRUPT_CORE0_TG0_T1_INTR_MAP_TG0_T1_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_TG0_T1_INTR_MAP_TG0_T1_INTR_MAP_S (0)
#define INTERRUPT_CORE0_TG0_T1_INTR_MAP_TG0_T1_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_TG0_WDT_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xD4))
#define INTERRUPT_CORE0_TG0_WDT_INTR_MAP_TG0_WDT_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_TG0_WDT_INTR_MAP_TG0_WDT_INTR_MAP_S (0)
#define INTERRUPT_CORE0_TG0_WDT_INTR_MAP_TG0_WDT_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_TG1_T0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xD8))
#define INTERRUPT_CORE0_TG1_T0_INTR_MAP_TG1_T0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_TG1_T0_INTR_MAP_TG1_T0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_TG1_T0_INTR_MAP_TG1_T0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_TG1_T1_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xDC))
#define INTERRUPT_CORE0_TG1_T1_INTR_MAP_TG1_T1_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_TG1_T1_INTR_MAP_TG1_T1_INTR_MAP_S (0)
#define INTERRUPT_CORE0_TG1_T1_INTR_MAP_TG1_T1_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_TG1_WDT_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xE0))
#define INTERRUPT_CORE0_TG1_WDT_INTR_MAP_TG1_WDT_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_TG1_WDT_INTR_MAP_TG1_WDT_INTR_MAP_S (0)
#define INTERRUPT_CORE0_TG1_WDT_INTR_MAP_TG1_WDT_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_SYSTIMER_TARGET0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xE4))
#define INTERRUPT_CORE0_SYSTIMER_TARGET0_INTR_MAP_SYSTIMER_TARGET0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_SYSTIMER_TARGET0_INTR_MAP_SYSTIMER_TARGET0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_SYSTIMER_TARGET0_INTR_MAP_SYSTIMER_TARGET0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_SYSTIMER_TARGET1_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xE8))
#define INTERRUPT_CORE0_SYSTIMER_TARGET1_INTR_MAP_SYSTIMER_TARGET1_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_SYSTIMER_TARGET1_INTR_MAP_SYSTIMER_TARGET1_INTR_MAP_S (0)
#define INTERRUPT_CORE0_SYSTIMER_TARGET1_INTR_MAP_SYSTIMER_TARGET1_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_SYSTIMER_TARGET2_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xEC))
#define INTERRUPT_CORE0_SYSTIMER_TARGET2_INTR_MAP_SYSTIMER_TARGET2_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_SYSTIMER_TARGET2_INTR_MAP_SYSTIMER_TARGET2_INTR_MAP_S (0)
#define INTERRUPT_CORE0_SYSTIMER_TARGET2_INTR_MAP_SYSTIMER_TARGET2_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_APB_ADC_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xF0))
#define INTERRUPT_CORE0_APB_ADC_INTR_MAP_APB_ADC_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_APB_ADC_INTR_MAP_APB_ADC_INTR_MAP_S (0)
#define INTERRUPT_CORE0_APB_ADC_INTR_MAP_APB_ADC_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_PWM_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xF4))
#define INTERRUPT_CORE0_PWM_INTR_MAP_PWM_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_PWM_INTR_MAP_PWM_INTR_MAP_S (0)
#define INTERRUPT_CORE0_PWM_INTR_MAP_PWM_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_PCNT_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xF8))
#define INTERRUPT_CORE0_PCNT_INTR_MAP_PCNT_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_PCNT_INTR_MAP_PCNT_INTR_MAP_S (0)
#define INTERRUPT_CORE0_PCNT_INTR_MAP_PCNT_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_PARL_IO_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0xFC))
#define INTERRUPT_CORE0_PARL_IO_INTR_MAP_PARL_IO_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_PARL_IO_INTR_MAP_PARL_IO_INTR_MAP_S (0)
#define INTERRUPT_CORE0_PARL_IO_INTR_MAP_PARL_IO_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_SLC0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x100))
#define INTERRUPT_CORE0_SLC0_INTR_MAP_SLC0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_SLC0_INTR_MAP_SLC0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_SLC0_INTR_MAP_SLC0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_SLC1_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x104))
#define INTERRUPT_CORE0_SLC1_INTR_MAP_SLC1_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_SLC1_INTR_MAP_SLC1_INTR_MAP_S (0)
#define INTERRUPT_CORE0_SLC1_INTR_MAP_SLC1_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_DMA_IN_CH0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x108))
#define INTERRUPT_CORE0_DMA_IN_CH0_INTR_MAP_DMA_IN_CH0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_DMA_IN_CH0_INTR_MAP_DMA_IN_CH0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_DMA_IN_CH0_INTR_MAP_DMA_IN_CH0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_DMA_IN_CH1_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x10C))
#define INTERRUPT_CORE0_DMA_IN_CH1_INTR_MAP_DMA_IN_CH1_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_DMA_IN_CH1_INTR_MAP_DMA_IN_CH1_INTR_MAP_S (0)
#define INTERRUPT_CORE0_DMA_IN_CH1_INTR_MAP_DMA_IN_CH1_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_DMA_IN_CH2_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x110))
#define INTERRUPT_CORE0_DMA_IN_CH2_INTR_MAP_DMA_IN_CH2_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_DMA_IN_CH2_INTR_MAP_DMA_IN_CH2_INTR_MAP_S (0)
#define INTERRUPT_CORE0_DMA_IN_CH2_INTR_MAP_DMA_IN_CH2_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_DMA_OUT_CH0_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x114))
#define INTERRUPT_CORE0_DMA_OUT_CH0_INTR_MAP_DMA_OUT_CH0_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_DMA_OUT_CH0_INTR_MAP_DMA_OUT_CH0_INTR_MAP_S (0)
#define INTERRUPT_CORE0_DMA_OUT_CH0_INTR_MAP_DMA_OUT_CH0_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_DMA_OUT_CH1_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x118))
#define INTERRUPT_CORE0_DMA_OUT_CH1_INTR_MAP_DMA_OUT_CH1_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_DMA_OUT_CH1_INTR_MAP_DMA_OUT_CH1_INTR_MAP_S (0)
#define INTERRUPT_CORE0_DMA_OUT_CH1_INTR_MAP_DMA_OUT_CH1_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_DMA_OUT_CH2_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x11C))
#define INTERRUPT_CORE0_DMA_OUT_CH2_INTR_MAP_DMA_OUT_CH2_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_DMA_OUT_CH2_INTR_MAP_DMA_OUT_CH2_INTR_MAP_S (0)
#define INTERRUPT_CORE0_DMA_OUT_CH2_INTR_MAP_DMA_OUT_CH2_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_GPSPI2_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x120))
#define INTERRUPT_CORE0_GPSPI2_INTR_MAP_GPSPI2_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_GPSPI2_INTR_MAP_GPSPI2_INTR_MAP_S (0)
#define INTERRUPT_CORE0_GPSPI2_INTR_MAP_GPSPI2_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_AES_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x124))
#define INTERRUPT_CORE0_AES_INTR_MAP_AES_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_AES_INTR_MAP_AES_INTR_MAP_S (0)
#define INTERRUPT_CORE0_AES_INTR_MAP_AES_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_SHA_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x128))
#define INTERRUPT_CORE0_SHA_INTR_MAP_SHA_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_SHA_INTR_MAP_SHA_INTR_MAP_S (0)
#define INTERRUPT_CORE0_SHA_INTR_MAP_SHA_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_RSA_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x12C))
#define INTERRUPT_CORE0_RSA_INTR_MAP_RSA_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_RSA_INTR_MAP_RSA_INTR_MAP_S (0)
#define INTERRUPT_CORE0_RSA_INTR_MAP_RSA_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_ECC_INTR_MAP_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x130))
#define INTERRUPT_CORE0_ECC_INTR_MAP_ECC_INTR_MAP_M (0x0000001FU)
#define INTERRUPT_CORE0_ECC_INTR_MAP_ECC_INTR_MAP_S (0)
#define INTERRUPT_CORE0_ECC_INTR_MAP_ECC_INTR_MAP_V(v) (((v) << 0) & 0x0000001FU)

// register description
#define INTERRUPT_CORE0_INTR_STATUS_REG_0_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x134))
#define INTERRUPT_CORE0_INTR_STATUS_REG_0_INTR_STATUS_0_M (0xFFFFFFFFU)
#define INTERRUPT_CORE0_INTR_STATUS_REG_0_INTR_STATUS_0_S (0)
#define INTERRUPT_CORE0_INTR_STATUS_REG_0_INTR_STATUS_0_V(v) (((v) << 0) & 0xFFFFFFFFU)

// register description
#define INTERRUPT_CORE0_INTR_STATUS_REG_1_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x138))
#define INTERRUPT_CORE0_INTR_STATUS_REG_1_INTR_STATUS_1_M (0xFFFFFFFFU)
#define INTERRUPT_CORE0_INTR_STATUS_REG_1_INTR_STATUS_1_S (0)
#define INTERRUPT_CORE0_INTR_STATUS_REG_1_INTR_STATUS_1_V(v) (((v) << 0) & 0xFFFFFFFFU)

// register description
#define INTERRUPT_CORE0_INT_STATUS_REG_2_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x13C))
#define INTERRUPT_CORE0_INT_STATUS_REG_2_INT_STATUS_2_M (0xFFFFFFFFU)
#define INTERRUPT_CORE0_INT_STATUS_REG_2_INT_STATUS_2_S (0)
#define INTERRUPT_CORE0_INT_STATUS_REG_2_INT_STATUS_2_V(v) (((v) << 0) & 0xFFFFFFFFU)

// register description
#define INTERRUPT_CORE0_CLOCK_GATE_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x140))
#define INTERRUPT_CORE0_CLOCK_GATE_REG_CLK_EN_M (0x00000001U)
#define INTERRUPT_CORE0_CLOCK_GATE_REG_CLK_EN_S (0)
#define INTERRUPT_CORE0_CLOCK_GATE_REG_CLK_EN_V(v) (((v) << 0) & 0x00000001U)

// register description
#define INTERRUPT_CORE0_INTERRUPT_REG_DATE_REG ((volatile uint32_t *)(INTERRUPT_CORE0_BASE + 0x7FC))
#define INTERRUPT_CORE0_INTERRUPT_REG_DATE_INTERRUPT_REG_DATE_M (0x0FFFFFFFU)
#define INTERRUPT_CORE0_INTERRUPT_REG_DATE_INTERRUPT_REG_DATE_S (0)
#define INTERRUPT_CORE0_INTERRUPT_REG_DATE_INTERRUPT_REG_DATE_V(v) (((v) << 0) & 0x0FFFFFFFU)

#endif // INTERRUPT_CORE0_H
