/*
 * LP_AON.h
 * LP_AON Peripheral
 * Base Address: 0x600B1000
 */

#ifndef LP_AON_H
#define LP_AON_H

#include <stdint.h>

#define LP_AON_BASE 0x600B1000

// need_des
#define LP_AON_STORE0_REG ((volatile uint32_t *)(LP_AON_BASE + 0x0))
#define LP_AON_STORE0_LP_AON_STORE0_M (0xFFFFFFFFU)
#define LP_AON_STORE0_LP_AON_STORE0_S (0)
#define LP_AON_STORE0_LP_AON_STORE0_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_AON_STORE1_REG ((volatile uint32_t *)(LP_AON_BASE + 0x4))
#define LP_AON_STORE1_LP_AON_STORE1_M (0xFFFFFFFFU)
#define LP_AON_STORE1_LP_AON_STORE1_S (0)
#define LP_AON_STORE1_LP_AON_STORE1_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_AON_STORE2_REG ((volatile uint32_t *)(LP_AON_BASE + 0x8))
#define LP_AON_STORE2_LP_AON_STORE2_M (0xFFFFFFFFU)
#define LP_AON_STORE2_LP_AON_STORE2_S (0)
#define LP_AON_STORE2_LP_AON_STORE2_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_AON_STORE3_REG ((volatile uint32_t *)(LP_AON_BASE + 0xC))
#define LP_AON_STORE3_LP_AON_STORE3_M (0xFFFFFFFFU)
#define LP_AON_STORE3_LP_AON_STORE3_S (0)
#define LP_AON_STORE3_LP_AON_STORE3_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_AON_STORE4_REG ((volatile uint32_t *)(LP_AON_BASE + 0x10))
#define LP_AON_STORE4_LP_AON_STORE4_M (0xFFFFFFFFU)
#define LP_AON_STORE4_LP_AON_STORE4_S (0)
#define LP_AON_STORE4_LP_AON_STORE4_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_AON_STORE5_REG ((volatile uint32_t *)(LP_AON_BASE + 0x14))
#define LP_AON_STORE5_LP_AON_STORE5_M (0xFFFFFFFFU)
#define LP_AON_STORE5_LP_AON_STORE5_S (0)
#define LP_AON_STORE5_LP_AON_STORE5_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_AON_STORE6_REG ((volatile uint32_t *)(LP_AON_BASE + 0x18))
#define LP_AON_STORE6_LP_AON_STORE6_M (0xFFFFFFFFU)
#define LP_AON_STORE6_LP_AON_STORE6_S (0)
#define LP_AON_STORE6_LP_AON_STORE6_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_AON_STORE7_REG ((volatile uint32_t *)(LP_AON_BASE + 0x1C))
#define LP_AON_STORE7_LP_AON_STORE7_M (0xFFFFFFFFU)
#define LP_AON_STORE7_LP_AON_STORE7_S (0)
#define LP_AON_STORE7_LP_AON_STORE7_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_AON_STORE8_REG ((volatile uint32_t *)(LP_AON_BASE + 0x20))
#define LP_AON_STORE8_LP_AON_STORE8_M (0xFFFFFFFFU)
#define LP_AON_STORE8_LP_AON_STORE8_S (0)
#define LP_AON_STORE8_LP_AON_STORE8_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_AON_STORE9_REG ((volatile uint32_t *)(LP_AON_BASE + 0x24))
#define LP_AON_STORE9_LP_AON_STORE9_M (0xFFFFFFFFU)
#define LP_AON_STORE9_LP_AON_STORE9_S (0)
#define LP_AON_STORE9_LP_AON_STORE9_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_AON_GPIO_MUX_REG ((volatile uint32_t *)(LP_AON_BASE + 0x28))
#define LP_AON_GPIO_MUX_SEL_M (0x000000FFU)
#define LP_AON_GPIO_MUX_SEL_S (0)
#define LP_AON_GPIO_MUX_SEL_V(v) (((v) << 0) & 0x000000FFU)

// need_des
#define LP_AON_GPIO_HOLD0_REG ((volatile uint32_t *)(LP_AON_BASE + 0x2C))
#define LP_AON_GPIO_HOLD0_GPIO_HOLD0_M (0xFFFFFFFFU)
#define LP_AON_GPIO_HOLD0_GPIO_HOLD0_S (0)
#define LP_AON_GPIO_HOLD0_GPIO_HOLD0_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_AON_GPIO_HOLD1_REG ((volatile uint32_t *)(LP_AON_BASE + 0x30))
#define LP_AON_GPIO_HOLD1_GPIO_HOLD1_M (0xFFFFFFFFU)
#define LP_AON_GPIO_HOLD1_GPIO_HOLD1_S (0)
#define LP_AON_GPIO_HOLD1_GPIO_HOLD1_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_AON_SYS_CFG_REG ((volatile uint32_t *)(LP_AON_BASE + 0x34))
#define LP_AON_SYS_CFG_FORCE_DOWNLOAD_BOOT_M (0x40000000U)
#define LP_AON_SYS_CFG_FORCE_DOWNLOAD_BOOT_S (30)
#define LP_AON_SYS_CFG_FORCE_DOWNLOAD_BOOT_V(v) (((v) << 30) & 0x40000000U)
#define LP_AON_SYS_CFG_HPSYS_SW_RESET_M (0x80000000U)
#define LP_AON_SYS_CFG_HPSYS_SW_RESET_S (31)
#define LP_AON_SYS_CFG_HPSYS_SW_RESET_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_AON_CPUCORE0_CFG_REG ((volatile uint32_t *)(LP_AON_BASE + 0x38))
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_SW_STALL_M (0x000000FFU)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_SW_STALL_S (0)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_SW_STALL_V(v) (((v) << 0) & 0x000000FFU)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_SW_RESET_M (0x10000000U)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_SW_RESET_S (28)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_SW_RESET_V(v) (((v) << 28) & 0x10000000U)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_OCD_HALT_ON_RESET_M (0x20000000U)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_OCD_HALT_ON_RESET_S (29)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_OCD_HALT_ON_RESET_V(v) (((v) << 29) & 0x20000000U)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_STAT_VECTOR_SEL_M (0x40000000U)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_STAT_VECTOR_SEL_S (30)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_STAT_VECTOR_SEL_V(v) (((v) << 30) & 0x40000000U)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_DRESET_MASK_M (0x80000000U)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_DRESET_MASK_S (31)
#define LP_AON_CPUCORE0_CFG_CPU_CORE0_DRESET_MASK_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_AON_IO_MUX_REG ((volatile uint32_t *)(LP_AON_BASE + 0x3C))
#define LP_AON_IO_MUX_RESET_DISABLE_M (0x80000000U)
#define LP_AON_IO_MUX_RESET_DISABLE_S (31)
#define LP_AON_IO_MUX_RESET_DISABLE_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_AON_EXT_WAKEUP_CNTL_REG ((volatile uint32_t *)(LP_AON_BASE + 0x40))
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_STATUS_M (0x000000FFU)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_STATUS_S (0)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_STATUS_V(v) (((v) << 0) & 0x000000FFU)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_STATUS_CLR_M (0x00004000U)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_STATUS_CLR_S (14)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_STATUS_CLR_V(v) (((v) << 14) & 0x00004000U)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_SEL_M (0x007F8000U)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_SEL_S (15)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_SEL_V(v) (((v) << 15) & 0x007F8000U)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_LV_M (0x7F800000U)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_LV_S (23)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_LV_V(v) (((v) << 23) & 0x7F800000U)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_FILTER_M (0x80000000U)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_FILTER_S (31)
#define LP_AON_EXT_WAKEUP_CNTL_EXT_WAKEUP_FILTER_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_AON_USB_REG ((volatile uint32_t *)(LP_AON_BASE + 0x44))
#define LP_AON_USB_RESET_DISABLE_M (0x80000000U)
#define LP_AON_USB_RESET_DISABLE_S (31)
#define LP_AON_USB_RESET_DISABLE_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_AON_LPBUS_REG ((volatile uint32_t *)(LP_AON_BASE + 0x48))
#define LP_AON_LPBUS_FAST_MEM_WPULSE_M (0x00070000U)
#define LP_AON_LPBUS_FAST_MEM_WPULSE_S (16)
#define LP_AON_LPBUS_FAST_MEM_WPULSE_V(v) (((v) << 16) & 0x00070000U)
#define LP_AON_LPBUS_FAST_MEM_WA_M (0x00380000U)
#define LP_AON_LPBUS_FAST_MEM_WA_S (19)
#define LP_AON_LPBUS_FAST_MEM_WA_V(v) (((v) << 19) & 0x00380000U)
#define LP_AON_LPBUS_FAST_MEM_RA_M (0x00C00000U)
#define LP_AON_LPBUS_FAST_MEM_RA_S (22)
#define LP_AON_LPBUS_FAST_MEM_RA_V(v) (((v) << 22) & 0x00C00000U)
#define LP_AON_LPBUS_FAST_MEM_MUX_FSM_IDLE_M (0x10000000U)
#define LP_AON_LPBUS_FAST_MEM_MUX_FSM_IDLE_S (28)
#define LP_AON_LPBUS_FAST_MEM_MUX_FSM_IDLE_V(v) (((v) << 28) & 0x10000000U)
#define LP_AON_LPBUS_FAST_MEM_MUX_SEL_STATUS_M (0x20000000U)
#define LP_AON_LPBUS_FAST_MEM_MUX_SEL_STATUS_S (29)
#define LP_AON_LPBUS_FAST_MEM_MUX_SEL_STATUS_V(v) (((v) << 29) & 0x20000000U)
#define LP_AON_LPBUS_FAST_MEM_MUX_SEL_UPDATE_M (0x40000000U)
#define LP_AON_LPBUS_FAST_MEM_MUX_SEL_UPDATE_S (30)
#define LP_AON_LPBUS_FAST_MEM_MUX_SEL_UPDATE_V(v) (((v) << 30) & 0x40000000U)
#define LP_AON_LPBUS_FAST_MEM_MUX_SEL_M (0x80000000U)
#define LP_AON_LPBUS_FAST_MEM_MUX_SEL_S (31)
#define LP_AON_LPBUS_FAST_MEM_MUX_SEL_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_AON_SDIO_ACTIVE_REG ((volatile uint32_t *)(LP_AON_BASE + 0x4C))
#define LP_AON_SDIO_ACTIVE_SDIO_ACT_DNUM_M (0xFFC00000U)
#define LP_AON_SDIO_ACTIVE_SDIO_ACT_DNUM_S (22)
#define LP_AON_SDIO_ACTIVE_SDIO_ACT_DNUM_V(v) (((v) << 22) & 0xFFC00000U)

// need_des
#define LP_AON_LPCORE_REG ((volatile uint32_t *)(LP_AON_BASE + 0x50))
#define LP_AON_LPCORE_ETM_WAKEUP_FLAG_CLR_M (0x00000001U)
#define LP_AON_LPCORE_ETM_WAKEUP_FLAG_CLR_S (0)
#define LP_AON_LPCORE_ETM_WAKEUP_FLAG_CLR_V(v) (((v) << 0) & 0x00000001U)
#define LP_AON_LPCORE_ETM_WAKEUP_FLAG_M (0x00000002U)
#define LP_AON_LPCORE_ETM_WAKEUP_FLAG_S (1)
#define LP_AON_LPCORE_ETM_WAKEUP_FLAG_V(v) (((v) << 1) & 0x00000002U)
#define LP_AON_LPCORE_DISABLE_M (0x80000000U)
#define LP_AON_LPCORE_DISABLE_S (31)
#define LP_AON_LPCORE_DISABLE_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_AON_SAR_CCT_REG ((volatile uint32_t *)(LP_AON_BASE + 0x54))
#define LP_AON_SAR_CCT_SAR2_PWDET_CCT_M (0xE0000000U)
#define LP_AON_SAR_CCT_SAR2_PWDET_CCT_S (29)
#define LP_AON_SAR_CCT_SAR2_PWDET_CCT_V(v) (((v) << 29) & 0xE0000000U)

// need_des
#define LP_AON_DATE_REG ((volatile uint32_t *)(LP_AON_BASE + 0x3FC))
#define LP_AON_DATE_DATE_M (0x7FFFFFFFU)
#define LP_AON_DATE_DATE_S (0)
#define LP_AON_DATE_DATE_V(v) (((v) << 0) & 0x7FFFFFFFU)
#define LP_AON_DATE_CLK_EN_M (0x80000000U)
#define LP_AON_DATE_CLK_EN_S (31)
#define LP_AON_DATE_CLK_EN_V(v) (((v) << 31) & 0x80000000U)

#endif // LP_AON_H
