/*
 * LP_TIMER.h
 * Low-power Timer
 * Base Address: 0x600B0C00
 */

#ifndef LP_TIMER_H
#define LP_TIMER_H

#include <stdint.h>

#define LP_TIMER_BASE 0x600B0C00

// need_des
#define LP_TIMER_TAR0_LOW_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x0))
#define LP_TIMER_TAR0_LOW_MAIN_TIMER_TAR_LOW0_M (0xFFFFFFFFU)
#define LP_TIMER_TAR0_LOW_MAIN_TIMER_TAR_LOW0_S (0)
#define LP_TIMER_TAR0_LOW_MAIN_TIMER_TAR_LOW0_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_TIMER_TAR0_HIGH_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x4))
#define LP_TIMER_TAR0_HIGH_MAIN_TIMER_TAR_HIGH0_M (0x0000FFFFU)
#define LP_TIMER_TAR0_HIGH_MAIN_TIMER_TAR_HIGH0_S (0)
#define LP_TIMER_TAR0_HIGH_MAIN_TIMER_TAR_HIGH0_V(v) (((v) << 0) & 0x0000FFFFU)
#define LP_TIMER_TAR0_HIGH_MAIN_TIMER_TAR_EN0_M (0x80000000U)
#define LP_TIMER_TAR0_HIGH_MAIN_TIMER_TAR_EN0_S (31)
#define LP_TIMER_TAR0_HIGH_MAIN_TIMER_TAR_EN0_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_TIMER_TAR1_LOW_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x8))
#define LP_TIMER_TAR1_LOW_MAIN_TIMER_TAR_LOW1_M (0xFFFFFFFFU)
#define LP_TIMER_TAR1_LOW_MAIN_TIMER_TAR_LOW1_S (0)
#define LP_TIMER_TAR1_LOW_MAIN_TIMER_TAR_LOW1_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_TIMER_TAR1_HIGH_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0xC))
#define LP_TIMER_TAR1_HIGH_MAIN_TIMER_TAR_HIGH1_M (0x0000FFFFU)
#define LP_TIMER_TAR1_HIGH_MAIN_TIMER_TAR_HIGH1_S (0)
#define LP_TIMER_TAR1_HIGH_MAIN_TIMER_TAR_HIGH1_V(v) (((v) << 0) & 0x0000FFFFU)
#define LP_TIMER_TAR1_HIGH_MAIN_TIMER_TAR_EN1_M (0x80000000U)
#define LP_TIMER_TAR1_HIGH_MAIN_TIMER_TAR_EN1_S (31)
#define LP_TIMER_TAR1_HIGH_MAIN_TIMER_TAR_EN1_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_TIMER_UPDATE_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x10))
#define LP_TIMER_UPDATE_MAIN_TIMER_UPDATE_M (0x10000000U)
#define LP_TIMER_UPDATE_MAIN_TIMER_UPDATE_S (28)
#define LP_TIMER_UPDATE_MAIN_TIMER_UPDATE_V(v) (((v) << 28) & 0x10000000U)
#define LP_TIMER_UPDATE_MAIN_TIMER_XTAL_OFF_M (0x20000000U)
#define LP_TIMER_UPDATE_MAIN_TIMER_XTAL_OFF_S (29)
#define LP_TIMER_UPDATE_MAIN_TIMER_XTAL_OFF_V(v) (((v) << 29) & 0x20000000U)
#define LP_TIMER_UPDATE_MAIN_TIMER_SYS_STALL_M (0x40000000U)
#define LP_TIMER_UPDATE_MAIN_TIMER_SYS_STALL_S (30)
#define LP_TIMER_UPDATE_MAIN_TIMER_SYS_STALL_V(v) (((v) << 30) & 0x40000000U)
#define LP_TIMER_UPDATE_MAIN_TIMER_SYS_RST_M (0x80000000U)
#define LP_TIMER_UPDATE_MAIN_TIMER_SYS_RST_S (31)
#define LP_TIMER_UPDATE_MAIN_TIMER_SYS_RST_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_TIMER_MAIN_BUF0_LOW_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x14))
#define LP_TIMER_MAIN_BUF0_LOW_MAIN_TIMER_BUF0_LOW_M (0xFFFFFFFFU)
#define LP_TIMER_MAIN_BUF0_LOW_MAIN_TIMER_BUF0_LOW_S (0)
#define LP_TIMER_MAIN_BUF0_LOW_MAIN_TIMER_BUF0_LOW_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_TIMER_MAIN_BUF0_HIGH_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x18))
#define LP_TIMER_MAIN_BUF0_HIGH_MAIN_TIMER_BUF0_HIGH_M (0x0000FFFFU)
#define LP_TIMER_MAIN_BUF0_HIGH_MAIN_TIMER_BUF0_HIGH_S (0)
#define LP_TIMER_MAIN_BUF0_HIGH_MAIN_TIMER_BUF0_HIGH_V(v) (((v) << 0) & 0x0000FFFFU)

// need_des
#define LP_TIMER_MAIN_BUF1_LOW_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x1C))
#define LP_TIMER_MAIN_BUF1_LOW_MAIN_TIMER_BUF1_LOW_M (0xFFFFFFFFU)
#define LP_TIMER_MAIN_BUF1_LOW_MAIN_TIMER_BUF1_LOW_S (0)
#define LP_TIMER_MAIN_BUF1_LOW_MAIN_TIMER_BUF1_LOW_V(v) (((v) << 0) & 0xFFFFFFFFU)

// need_des
#define LP_TIMER_MAIN_BUF1_HIGH_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x20))
#define LP_TIMER_MAIN_BUF1_HIGH_MAIN_TIMER_BUF1_HIGH_M (0x0000FFFFU)
#define LP_TIMER_MAIN_BUF1_HIGH_MAIN_TIMER_BUF1_HIGH_S (0)
#define LP_TIMER_MAIN_BUF1_HIGH_MAIN_TIMER_BUF1_HIGH_V(v) (((v) << 0) & 0x0000FFFFU)

// need_des
#define LP_TIMER_MAIN_OVERFLOW_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x24))
#define LP_TIMER_MAIN_OVERFLOW_MAIN_TIMER_ALARM_LOAD_M (0x80000000U)
#define LP_TIMER_MAIN_OVERFLOW_MAIN_TIMER_ALARM_LOAD_S (31)
#define LP_TIMER_MAIN_OVERFLOW_MAIN_TIMER_ALARM_LOAD_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_TIMER_INT_RAW_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x28))
#define LP_TIMER_INT_RAW_OVERFLOW_RAW_M (0x40000000U)
#define LP_TIMER_INT_RAW_OVERFLOW_RAW_S (30)
#define LP_TIMER_INT_RAW_OVERFLOW_RAW_V(v) (((v) << 30) & 0x40000000U)
#define LP_TIMER_INT_RAW_SOC_WAKEUP_INT_RAW_M (0x80000000U)
#define LP_TIMER_INT_RAW_SOC_WAKEUP_INT_RAW_S (31)
#define LP_TIMER_INT_RAW_SOC_WAKEUP_INT_RAW_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_TIMER_INT_ST_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x2C))
#define LP_TIMER_INT_ST_OVERFLOW_ST_M (0x40000000U)
#define LP_TIMER_INT_ST_OVERFLOW_ST_S (30)
#define LP_TIMER_INT_ST_OVERFLOW_ST_V(v) (((v) << 30) & 0x40000000U)
#define LP_TIMER_INT_ST_SOC_WAKEUP_INT_ST_M (0x80000000U)
#define LP_TIMER_INT_ST_SOC_WAKEUP_INT_ST_S (31)
#define LP_TIMER_INT_ST_SOC_WAKEUP_INT_ST_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_TIMER_INT_ENA_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x30))
#define LP_TIMER_INT_ENA_OVERFLOW_ENA_M (0x40000000U)
#define LP_TIMER_INT_ENA_OVERFLOW_ENA_S (30)
#define LP_TIMER_INT_ENA_OVERFLOW_ENA_V(v) (((v) << 30) & 0x40000000U)
#define LP_TIMER_INT_ENA_SOC_WAKEUP_INT_ENA_M (0x80000000U)
#define LP_TIMER_INT_ENA_SOC_WAKEUP_INT_ENA_S (31)
#define LP_TIMER_INT_ENA_SOC_WAKEUP_INT_ENA_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_TIMER_INT_CLR_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x34))
#define LP_TIMER_INT_CLR_OVERFLOW_CLR_M (0x40000000U)
#define LP_TIMER_INT_CLR_OVERFLOW_CLR_S (30)
#define LP_TIMER_INT_CLR_OVERFLOW_CLR_V(v) (((v) << 30) & 0x40000000U)
#define LP_TIMER_INT_CLR_SOC_WAKEUP_INT_CLR_M (0x80000000U)
#define LP_TIMER_INT_CLR_SOC_WAKEUP_INT_CLR_S (31)
#define LP_TIMER_INT_CLR_SOC_WAKEUP_INT_CLR_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_TIMER_LP_INT_RAW_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x38))
#define LP_TIMER_LP_INT_RAW_MAIN_TIMER_OVERFLOW_LP_INT_RAW_M (0x40000000U)
#define LP_TIMER_LP_INT_RAW_MAIN_TIMER_OVERFLOW_LP_INT_RAW_S (30)
#define LP_TIMER_LP_INT_RAW_MAIN_TIMER_OVERFLOW_LP_INT_RAW_V(v) (((v) << 30) & 0x40000000U)
#define LP_TIMER_LP_INT_RAW_MAIN_TIMER_LP_INT_RAW_M (0x80000000U)
#define LP_TIMER_LP_INT_RAW_MAIN_TIMER_LP_INT_RAW_S (31)
#define LP_TIMER_LP_INT_RAW_MAIN_TIMER_LP_INT_RAW_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_TIMER_LP_INT_ST_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x3C))
#define LP_TIMER_LP_INT_ST_MAIN_TIMER_OVERFLOW_LP_INT_ST_M (0x40000000U)
#define LP_TIMER_LP_INT_ST_MAIN_TIMER_OVERFLOW_LP_INT_ST_S (30)
#define LP_TIMER_LP_INT_ST_MAIN_TIMER_OVERFLOW_LP_INT_ST_V(v) (((v) << 30) & 0x40000000U)
#define LP_TIMER_LP_INT_ST_MAIN_TIMER_LP_INT_ST_M (0x80000000U)
#define LP_TIMER_LP_INT_ST_MAIN_TIMER_LP_INT_ST_S (31)
#define LP_TIMER_LP_INT_ST_MAIN_TIMER_LP_INT_ST_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_TIMER_LP_INT_ENA_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x40))
#define LP_TIMER_LP_INT_ENA_MAIN_TIMER_OVERFLOW_LP_INT_ENA_M (0x40000000U)
#define LP_TIMER_LP_INT_ENA_MAIN_TIMER_OVERFLOW_LP_INT_ENA_S (30)
#define LP_TIMER_LP_INT_ENA_MAIN_TIMER_OVERFLOW_LP_INT_ENA_V(v) (((v) << 30) & 0x40000000U)
#define LP_TIMER_LP_INT_ENA_MAIN_TIMER_LP_INT_ENA_M (0x80000000U)
#define LP_TIMER_LP_INT_ENA_MAIN_TIMER_LP_INT_ENA_S (31)
#define LP_TIMER_LP_INT_ENA_MAIN_TIMER_LP_INT_ENA_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_TIMER_LP_INT_CLR_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x44))
#define LP_TIMER_LP_INT_CLR_MAIN_TIMER_OVERFLOW_LP_INT_CLR_M (0x40000000U)
#define LP_TIMER_LP_INT_CLR_MAIN_TIMER_OVERFLOW_LP_INT_CLR_S (30)
#define LP_TIMER_LP_INT_CLR_MAIN_TIMER_OVERFLOW_LP_INT_CLR_V(v) (((v) << 30) & 0x40000000U)
#define LP_TIMER_LP_INT_CLR_MAIN_TIMER_LP_INT_CLR_M (0x80000000U)
#define LP_TIMER_LP_INT_CLR_MAIN_TIMER_LP_INT_CLR_S (31)
#define LP_TIMER_LP_INT_CLR_MAIN_TIMER_LP_INT_CLR_V(v) (((v) << 31) & 0x80000000U)

// need_des
#define LP_TIMER_DATE_REG ((volatile uint32_t *)(LP_TIMER_BASE + 0x3FC))
#define LP_TIMER_DATE_DATE_M (0x7FFFFFFFU)
#define LP_TIMER_DATE_DATE_S (0)
#define LP_TIMER_DATE_DATE_V(v) (((v) << 0) & 0x7FFFFFFFU)
#define LP_TIMER_DATE_CLK_EN_M (0x80000000U)
#define LP_TIMER_DATE_CLK_EN_S (31)
#define LP_TIMER_DATE_CLK_EN_V(v) (((v) << 31) & 0x80000000U)

#endif // LP_TIMER_H
