/*
 * MEM_MONITOR.h
 * MEM_MONITOR Peripheral
 * Base Address: 0x60092000
 */

#ifndef MEM_MONITOR_H
#define MEM_MONITOR_H

#include <stdint.h>

#define MEM_MONITOR_BASE 0x60092000

// log config regsiter
#define MEM_MONITOR_LOG_SETTING_REG ((volatile uint32_t *)(MEM_MONITOR_BASE + 0x0))
#define MEM_MONITOR_LOG_SETTING_LOG_ENA_M (0x00000007U)
#define MEM_MONITOR_LOG_SETTING_LOG_ENA_S (0)
#define MEM_MONITOR_LOG_SETTING_LOG_ENA_V(v) (((v) << 0) & 0x00000007U)
#define MEM_MONITOR_LOG_SETTING_LOG_MODE_M (0x00000078U)
#define MEM_MONITOR_LOG_SETTING_LOG_MODE_S (3)
#define MEM_MONITOR_LOG_SETTING_LOG_MODE_V(v) (((v) << 3) & 0x00000078U)
#define MEM_MONITOR_LOG_SETTING_LOG_MEM_LOOP_ENABLE_M (0x00000080U)
#define MEM_MONITOR_LOG_SETTING_LOG_MEM_LOOP_ENABLE_S (7)
#define MEM_MONITOR_LOG_SETTING_LOG_MEM_LOOP_ENABLE_V(v) (((v) << 7) & 0x00000080U)

// check data regsiter
#define MEM_MONITOR_LOG_CHECK_DATA_REG ((volatile uint32_t *)(MEM_MONITOR_BASE + 0x4))
#define MEM_MONITOR_LOG_CHECK_DATA_LOG_CHECK_DATA_M (0xFFFFFFFFU)
#define MEM_MONITOR_LOG_CHECK_DATA_LOG_CHECK_DATA_S (0)
#define MEM_MONITOR_LOG_CHECK_DATA_LOG_CHECK_DATA_V(v) (((v) << 0) & 0xFFFFFFFFU)

// check data mask register
#define MEM_MONITOR_LOG_DATA_MASK_REG ((volatile uint32_t *)(MEM_MONITOR_BASE + 0x8))
#define MEM_MONITOR_LOG_DATA_MASK_LOG_DATA_MASK_M (0x0000000FU)
#define MEM_MONITOR_LOG_DATA_MASK_LOG_DATA_MASK_S (0)
#define MEM_MONITOR_LOG_DATA_MASK_LOG_DATA_MASK_V(v) (((v) << 0) & 0x0000000FU)

// log boundary regsiter
#define MEM_MONITOR_LOG_MIN_REG ((volatile uint32_t *)(MEM_MONITOR_BASE + 0xC))
#define MEM_MONITOR_LOG_MIN_LOG_MIN_M (0xFFFFFFFFU)
#define MEM_MONITOR_LOG_MIN_LOG_MIN_S (0)
#define MEM_MONITOR_LOG_MIN_LOG_MIN_V(v) (((v) << 0) & 0xFFFFFFFFU)

// log boundary regsiter
#define MEM_MONITOR_LOG_MAX_REG ((volatile uint32_t *)(MEM_MONITOR_BASE + 0x10))
#define MEM_MONITOR_LOG_MAX_LOG_MAX_M (0xFFFFFFFFU)
#define MEM_MONITOR_LOG_MAX_LOG_MAX_S (0)
#define MEM_MONITOR_LOG_MAX_LOG_MAX_V(v) (((v) << 0) & 0xFFFFFFFFU)

// log message store range register
#define MEM_MONITOR_LOG_MEM_START_REG ((volatile uint32_t *)(MEM_MONITOR_BASE + 0x14))
#define MEM_MONITOR_LOG_MEM_START_LOG_MEM_START_M (0xFFFFFFFFU)
#define MEM_MONITOR_LOG_MEM_START_LOG_MEM_START_S (0)
#define MEM_MONITOR_LOG_MEM_START_LOG_MEM_START_V(v) (((v) << 0) & 0xFFFFFFFFU)

// log message store range register
#define MEM_MONITOR_LOG_MEM_END_REG ((volatile uint32_t *)(MEM_MONITOR_BASE + 0x18))
#define MEM_MONITOR_LOG_MEM_END_LOG_MEM_END_M (0xFFFFFFFFU)
#define MEM_MONITOR_LOG_MEM_END_LOG_MEM_END_S (0)
#define MEM_MONITOR_LOG_MEM_END_LOG_MEM_END_V(v) (((v) << 0) & 0xFFFFFFFFU)

// current writing address.
#define MEM_MONITOR_LOG_MEM_CURRENT_ADDR_REG ((volatile uint32_t *)(MEM_MONITOR_BASE + 0x1C))
#define MEM_MONITOR_LOG_MEM_CURRENT_ADDR_LOG_MEM_CURRENT_ADDR_M (0xFFFFFFFFU)
#define MEM_MONITOR_LOG_MEM_CURRENT_ADDR_LOG_MEM_CURRENT_ADDR_S (0)
#define MEM_MONITOR_LOG_MEM_CURRENT_ADDR_LOG_MEM_CURRENT_ADDR_V(v) (((v) << 0) & 0xFFFFFFFFU)

// writing address update
#define MEM_MONITOR_LOG_MEM_ADDR_UPDATE_REG ((volatile uint32_t *)(MEM_MONITOR_BASE + 0x20))
#define MEM_MONITOR_LOG_MEM_ADDR_UPDATE_LOG_MEM_ADDR_UPDATE_M (0x00000001U)
#define MEM_MONITOR_LOG_MEM_ADDR_UPDATE_LOG_MEM_ADDR_UPDATE_S (0)
#define MEM_MONITOR_LOG_MEM_ADDR_UPDATE_LOG_MEM_ADDR_UPDATE_V(v) (((v) << 0) & 0x00000001U)

// full flag status register
#define MEM_MONITOR_LOG_MEM_FULL_FLAG_REG ((volatile uint32_t *)(MEM_MONITOR_BASE + 0x24))
#define MEM_MONITOR_LOG_MEM_FULL_FLAG_LOG_MEM_FULL_FLAG_M (0x00000001U)
#define MEM_MONITOR_LOG_MEM_FULL_FLAG_LOG_MEM_FULL_FLAG_S (0)
#define MEM_MONITOR_LOG_MEM_FULL_FLAG_LOG_MEM_FULL_FLAG_V(v) (((v) << 0) & 0x00000001U)
#define MEM_MONITOR_LOG_MEM_FULL_FLAG_CLR_LOG_MEM_FULL_FLAG_M (0x00000002U)
#define MEM_MONITOR_LOG_MEM_FULL_FLAG_CLR_LOG_MEM_FULL_FLAG_S (1)
#define MEM_MONITOR_LOG_MEM_FULL_FLAG_CLR_LOG_MEM_FULL_FLAG_V(v) (((v) << 1) & 0x00000002U)

// clock gate force on register
#define MEM_MONITOR_CLOCK_GATE_REG ((volatile uint32_t *)(MEM_MONITOR_BASE + 0x28))
#define MEM_MONITOR_CLOCK_GATE_CLK_EN_M (0x00000001U)
#define MEM_MONITOR_CLOCK_GATE_CLK_EN_S (0)
#define MEM_MONITOR_CLOCK_GATE_CLK_EN_V(v) (((v) << 0) & 0x00000001U)

// version register
#define MEM_MONITOR_DATE_REG ((volatile uint32_t *)(MEM_MONITOR_BASE + 0x3FC))
#define MEM_MONITOR_DATE_DATE_M (0x0FFFFFFFU)
#define MEM_MONITOR_DATE_DATE_S (0)
#define MEM_MONITOR_DATE_DATE_V(v) (((v) << 0) & 0x0FFFFFFFU)

#endif // MEM_MONITOR_H
