/*
 * SYSTIMER.h
 * System Timer
 * Base Address: 0x6000A000
 */

#ifndef SYSTIMER_H
#define SYSTIMER_H

#include <stdint.h>

#define SYSTIMER_BASE 0x6000A000

// Configure system timer clock
#define SYSTIMER_CONF_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x0))
#define SYSTIMER_CONF_SYSTIMER_CLK_FO_M (0x00000001U)
#define SYSTIMER_CONF_SYSTIMER_CLK_FO_S (0)
#define SYSTIMER_CONF_SYSTIMER_CLK_FO_V(v) (((v) << 0) & 0x00000001U)
#define SYSTIMER_CONF_ETM_EN_M (0x00000002U)
#define SYSTIMER_CONF_ETM_EN_S (1)
#define SYSTIMER_CONF_ETM_EN_V(v) (((v) << 1) & 0x00000002U)
#define SYSTIMER_CONF_TARGET2_WORK_EN_M (0x00400000U)
#define SYSTIMER_CONF_TARGET2_WORK_EN_S (22)
#define SYSTIMER_CONF_TARGET2_WORK_EN_V(v) (((v) << 22) & 0x00400000U)
#define SYSTIMER_CONF_TARGET1_WORK_EN_M (0x00800000U)
#define SYSTIMER_CONF_TARGET1_WORK_EN_S (23)
#define SYSTIMER_CONF_TARGET1_WORK_EN_V(v) (((v) << 23) & 0x00800000U)
#define SYSTIMER_CONF_TARGET0_WORK_EN_M (0x01000000U)
#define SYSTIMER_CONF_TARGET0_WORK_EN_S (24)
#define SYSTIMER_CONF_TARGET0_WORK_EN_V(v) (((v) << 24) & 0x01000000U)
#define SYSTIMER_CONF_TIMER_UNIT1_CORE1_STALL_EN_M (0x02000000U)
#define SYSTIMER_CONF_TIMER_UNIT1_CORE1_STALL_EN_S (25)
#define SYSTIMER_CONF_TIMER_UNIT1_CORE1_STALL_EN_V(v) (((v) << 25) & 0x02000000U)
#define SYSTIMER_CONF_TIMER_UNIT1_CORE0_STALL_EN_M (0x04000000U)
#define SYSTIMER_CONF_TIMER_UNIT1_CORE0_STALL_EN_S (26)
#define SYSTIMER_CONF_TIMER_UNIT1_CORE0_STALL_EN_V(v) (((v) << 26) & 0x04000000U)
#define SYSTIMER_CONF_TIMER_UNIT0_CORE1_STALL_EN_M (0x08000000U)
#define SYSTIMER_CONF_TIMER_UNIT0_CORE1_STALL_EN_S (27)
#define SYSTIMER_CONF_TIMER_UNIT0_CORE1_STALL_EN_V(v) (((v) << 27) & 0x08000000U)
#define SYSTIMER_CONF_TIMER_UNIT0_CORE0_STALL_EN_M (0x10000000U)
#define SYSTIMER_CONF_TIMER_UNIT0_CORE0_STALL_EN_S (28)
#define SYSTIMER_CONF_TIMER_UNIT0_CORE0_STALL_EN_V(v) (((v) << 28) & 0x10000000U)
#define SYSTIMER_CONF_TIMER_UNIT1_WORK_EN_M (0x20000000U)
#define SYSTIMER_CONF_TIMER_UNIT1_WORK_EN_S (29)
#define SYSTIMER_CONF_TIMER_UNIT1_WORK_EN_V(v) (((v) << 29) & 0x20000000U)
#define SYSTIMER_CONF_TIMER_UNIT0_WORK_EN_M (0x40000000U)
#define SYSTIMER_CONF_TIMER_UNIT0_WORK_EN_S (30)
#define SYSTIMER_CONF_TIMER_UNIT0_WORK_EN_V(v) (((v) << 30) & 0x40000000U)
#define SYSTIMER_CONF_CLK_EN_M (0x80000000U)
#define SYSTIMER_CONF_CLK_EN_S (31)
#define SYSTIMER_CONF_CLK_EN_V(v) (((v) << 31) & 0x80000000U)

// system timer unit0 value update register
#define SYSTIMER_UNIT0_OP_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x4))
#define SYSTIMER_UNIT0_OP_TIMER_UNIT0_VALUE_VALID_M (0x20000000U)
#define SYSTIMER_UNIT0_OP_TIMER_UNIT0_VALUE_VALID_S (29)
#define SYSTIMER_UNIT0_OP_TIMER_UNIT0_VALUE_VALID_V(v) (((v) << 29) & 0x20000000U)
#define SYSTIMER_UNIT0_OP_TIMER_UNIT0_UPDATE_M (0x40000000U)
#define SYSTIMER_UNIT0_OP_TIMER_UNIT0_UPDATE_S (30)
#define SYSTIMER_UNIT0_OP_TIMER_UNIT0_UPDATE_V(v) (((v) << 30) & 0x40000000U)

// system timer unit1 value update register
#define SYSTIMER_UNIT1_OP_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x8))
#define SYSTIMER_UNIT1_OP_TIMER_UNIT1_VALUE_VALID_M (0x20000000U)
#define SYSTIMER_UNIT1_OP_TIMER_UNIT1_VALUE_VALID_S (29)
#define SYSTIMER_UNIT1_OP_TIMER_UNIT1_VALUE_VALID_V(v) (((v) << 29) & 0x20000000U)
#define SYSTIMER_UNIT1_OP_TIMER_UNIT1_UPDATE_M (0x40000000U)
#define SYSTIMER_UNIT1_OP_TIMER_UNIT1_UPDATE_S (30)
#define SYSTIMER_UNIT1_OP_TIMER_UNIT1_UPDATE_V(v) (((v) << 30) & 0x40000000U)

// system timer unit0 value high load register
#define SYSTIMER_UNIT0_LOAD_HI_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0xC))
#define SYSTIMER_UNIT0_LOAD_HI_TIMER_UNIT0_LOAD_HI_M (0x000FFFFFU)
#define SYSTIMER_UNIT0_LOAD_HI_TIMER_UNIT0_LOAD_HI_S (0)
#define SYSTIMER_UNIT0_LOAD_HI_TIMER_UNIT0_LOAD_HI_V(v) (((v) << 0) & 0x000FFFFFU)

// system timer unit0 value low load register
#define SYSTIMER_UNIT0_LOAD_LO_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x10))
#define SYSTIMER_UNIT0_LOAD_LO_TIMER_UNIT0_LOAD_LO_M (0xFFFFFFFFU)
#define SYSTIMER_UNIT0_LOAD_LO_TIMER_UNIT0_LOAD_LO_S (0)
#define SYSTIMER_UNIT0_LOAD_LO_TIMER_UNIT0_LOAD_LO_V(v) (((v) << 0) & 0xFFFFFFFFU)

// system timer unit1 value high load register
#define SYSTIMER_UNIT1_LOAD_HI_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x14))
#define SYSTIMER_UNIT1_LOAD_HI_TIMER_UNIT1_LOAD_HI_M (0x000FFFFFU)
#define SYSTIMER_UNIT1_LOAD_HI_TIMER_UNIT1_LOAD_HI_S (0)
#define SYSTIMER_UNIT1_LOAD_HI_TIMER_UNIT1_LOAD_HI_V(v) (((v) << 0) & 0x000FFFFFU)

// system timer unit1 value low load register
#define SYSTIMER_UNIT1_LOAD_LO_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x18))
#define SYSTIMER_UNIT1_LOAD_LO_TIMER_UNIT1_LOAD_LO_M (0xFFFFFFFFU)
#define SYSTIMER_UNIT1_LOAD_LO_TIMER_UNIT1_LOAD_LO_S (0)
#define SYSTIMER_UNIT1_LOAD_LO_TIMER_UNIT1_LOAD_LO_V(v) (((v) << 0) & 0xFFFFFFFFU)

// system timer comp0 value high register
#define SYSTIMER_TARGET0_HI_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x1C))
#define SYSTIMER_TARGET0_HI_TIMER_TARGET0_HI_M (0x000FFFFFU)
#define SYSTIMER_TARGET0_HI_TIMER_TARGET0_HI_S (0)
#define SYSTIMER_TARGET0_HI_TIMER_TARGET0_HI_V(v) (((v) << 0) & 0x000FFFFFU)

// system timer comp0 value low register
#define SYSTIMER_TARGET0_LO_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x20))
#define SYSTIMER_TARGET0_LO_TIMER_TARGET0_LO_M (0xFFFFFFFFU)
#define SYSTIMER_TARGET0_LO_TIMER_TARGET0_LO_S (0)
#define SYSTIMER_TARGET0_LO_TIMER_TARGET0_LO_V(v) (((v) << 0) & 0xFFFFFFFFU)

// system timer comp1 value high register
#define SYSTIMER_TARGET1_HI_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x24))
#define SYSTIMER_TARGET1_HI_TIMER_TARGET1_HI_M (0x000FFFFFU)
#define SYSTIMER_TARGET1_HI_TIMER_TARGET1_HI_S (0)
#define SYSTIMER_TARGET1_HI_TIMER_TARGET1_HI_V(v) (((v) << 0) & 0x000FFFFFU)

// system timer comp1 value low register
#define SYSTIMER_TARGET1_LO_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x28))
#define SYSTIMER_TARGET1_LO_TIMER_TARGET1_LO_M (0xFFFFFFFFU)
#define SYSTIMER_TARGET1_LO_TIMER_TARGET1_LO_S (0)
#define SYSTIMER_TARGET1_LO_TIMER_TARGET1_LO_V(v) (((v) << 0) & 0xFFFFFFFFU)

// system timer comp2 value high register
#define SYSTIMER_TARGET2_HI_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x2C))
#define SYSTIMER_TARGET2_HI_TIMER_TARGET2_HI_M (0x000FFFFFU)
#define SYSTIMER_TARGET2_HI_TIMER_TARGET2_HI_S (0)
#define SYSTIMER_TARGET2_HI_TIMER_TARGET2_HI_V(v) (((v) << 0) & 0x000FFFFFU)

// system timer comp2 value low register
#define SYSTIMER_TARGET2_LO_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x30))
#define SYSTIMER_TARGET2_LO_TIMER_TARGET2_LO_M (0xFFFFFFFFU)
#define SYSTIMER_TARGET2_LO_TIMER_TARGET2_LO_S (0)
#define SYSTIMER_TARGET2_LO_TIMER_TARGET2_LO_V(v) (((v) << 0) & 0xFFFFFFFFU)

// system timer comp0 target mode register
#define SYSTIMER_TARGET0_CONF_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x34))
#define SYSTIMER_TARGET0_CONF_TARGET0_PERIOD_M (0x03FFFFFFU)
#define SYSTIMER_TARGET0_CONF_TARGET0_PERIOD_S (0)
#define SYSTIMER_TARGET0_CONF_TARGET0_PERIOD_V(v) (((v) << 0) & 0x03FFFFFFU)
#define SYSTIMER_TARGET0_CONF_TARGET0_PERIOD_MODE_M (0x40000000U)
#define SYSTIMER_TARGET0_CONF_TARGET0_PERIOD_MODE_S (30)
#define SYSTIMER_TARGET0_CONF_TARGET0_PERIOD_MODE_V(v) (((v) << 30) & 0x40000000U)
#define SYSTIMER_TARGET0_CONF_TARGET0_TIMER_UNIT_SEL_M (0x80000000U)
#define SYSTIMER_TARGET0_CONF_TARGET0_TIMER_UNIT_SEL_S (31)
#define SYSTIMER_TARGET0_CONF_TARGET0_TIMER_UNIT_SEL_V(v) (((v) << 31) & 0x80000000U)

// system timer comp1 target mode register
#define SYSTIMER_TARGET1_CONF_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x38))
#define SYSTIMER_TARGET1_CONF_TARGET1_PERIOD_M (0x03FFFFFFU)
#define SYSTIMER_TARGET1_CONF_TARGET1_PERIOD_S (0)
#define SYSTIMER_TARGET1_CONF_TARGET1_PERIOD_V(v) (((v) << 0) & 0x03FFFFFFU)
#define SYSTIMER_TARGET1_CONF_TARGET1_PERIOD_MODE_M (0x40000000U)
#define SYSTIMER_TARGET1_CONF_TARGET1_PERIOD_MODE_S (30)
#define SYSTIMER_TARGET1_CONF_TARGET1_PERIOD_MODE_V(v) (((v) << 30) & 0x40000000U)
#define SYSTIMER_TARGET1_CONF_TARGET1_TIMER_UNIT_SEL_M (0x80000000U)
#define SYSTIMER_TARGET1_CONF_TARGET1_TIMER_UNIT_SEL_S (31)
#define SYSTIMER_TARGET1_CONF_TARGET1_TIMER_UNIT_SEL_V(v) (((v) << 31) & 0x80000000U)

// system timer comp2 target mode register
#define SYSTIMER_TARGET2_CONF_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x3C))
#define SYSTIMER_TARGET2_CONF_TARGET2_PERIOD_M (0x03FFFFFFU)
#define SYSTIMER_TARGET2_CONF_TARGET2_PERIOD_S (0)
#define SYSTIMER_TARGET2_CONF_TARGET2_PERIOD_V(v) (((v) << 0) & 0x03FFFFFFU)
#define SYSTIMER_TARGET2_CONF_TARGET2_PERIOD_MODE_M (0x40000000U)
#define SYSTIMER_TARGET2_CONF_TARGET2_PERIOD_MODE_S (30)
#define SYSTIMER_TARGET2_CONF_TARGET2_PERIOD_MODE_V(v) (((v) << 30) & 0x40000000U)
#define SYSTIMER_TARGET2_CONF_TARGET2_TIMER_UNIT_SEL_M (0x80000000U)
#define SYSTIMER_TARGET2_CONF_TARGET2_TIMER_UNIT_SEL_S (31)
#define SYSTIMER_TARGET2_CONF_TARGET2_TIMER_UNIT_SEL_V(v) (((v) << 31) & 0x80000000U)

// system timer unit0 value high register
#define SYSTIMER_UNIT0_VALUE_HI_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x40))
#define SYSTIMER_UNIT0_VALUE_HI_TIMER_UNIT0_VALUE_HI_M (0x000FFFFFU)
#define SYSTIMER_UNIT0_VALUE_HI_TIMER_UNIT0_VALUE_HI_S (0)
#define SYSTIMER_UNIT0_VALUE_HI_TIMER_UNIT0_VALUE_HI_V(v) (((v) << 0) & 0x000FFFFFU)

// system timer unit0 value low register
#define SYSTIMER_UNIT0_VALUE_LO_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x44))
#define SYSTIMER_UNIT0_VALUE_LO_TIMER_UNIT0_VALUE_LO_M (0xFFFFFFFFU)
#define SYSTIMER_UNIT0_VALUE_LO_TIMER_UNIT0_VALUE_LO_S (0)
#define SYSTIMER_UNIT0_VALUE_LO_TIMER_UNIT0_VALUE_LO_V(v) (((v) << 0) & 0xFFFFFFFFU)

// system timer unit1 value high register
#define SYSTIMER_UNIT1_VALUE_HI_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x48))
#define SYSTIMER_UNIT1_VALUE_HI_TIMER_UNIT1_VALUE_HI_M (0x000FFFFFU)
#define SYSTIMER_UNIT1_VALUE_HI_TIMER_UNIT1_VALUE_HI_S (0)
#define SYSTIMER_UNIT1_VALUE_HI_TIMER_UNIT1_VALUE_HI_V(v) (((v) << 0) & 0x000FFFFFU)

// system timer unit1 value low register
#define SYSTIMER_UNIT1_VALUE_LO_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x4C))
#define SYSTIMER_UNIT1_VALUE_LO_TIMER_UNIT1_VALUE_LO_M (0xFFFFFFFFU)
#define SYSTIMER_UNIT1_VALUE_LO_TIMER_UNIT1_VALUE_LO_S (0)
#define SYSTIMER_UNIT1_VALUE_LO_TIMER_UNIT1_VALUE_LO_V(v) (((v) << 0) & 0xFFFFFFFFU)

// system timer comp0 conf sync register
#define SYSTIMER_COMP0_LOAD_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x50))
#define SYSTIMER_COMP0_LOAD_TIMER_COMP0_LOAD_M (0x00000001U)
#define SYSTIMER_COMP0_LOAD_TIMER_COMP0_LOAD_S (0)
#define SYSTIMER_COMP0_LOAD_TIMER_COMP0_LOAD_V(v) (((v) << 0) & 0x00000001U)

// system timer comp1 conf sync register
#define SYSTIMER_COMP1_LOAD_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x54))
#define SYSTIMER_COMP1_LOAD_TIMER_COMP1_LOAD_M (0x00000001U)
#define SYSTIMER_COMP1_LOAD_TIMER_COMP1_LOAD_S (0)
#define SYSTIMER_COMP1_LOAD_TIMER_COMP1_LOAD_V(v) (((v) << 0) & 0x00000001U)

// system timer comp2 conf sync register
#define SYSTIMER_COMP2_LOAD_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x58))
#define SYSTIMER_COMP2_LOAD_TIMER_COMP2_LOAD_M (0x00000001U)
#define SYSTIMER_COMP2_LOAD_TIMER_COMP2_LOAD_S (0)
#define SYSTIMER_COMP2_LOAD_TIMER_COMP2_LOAD_V(v) (((v) << 0) & 0x00000001U)

// system timer unit0 conf sync register
#define SYSTIMER_UNIT0_LOAD_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x5C))
#define SYSTIMER_UNIT0_LOAD_TIMER_UNIT0_LOAD_M (0x00000001U)
#define SYSTIMER_UNIT0_LOAD_TIMER_UNIT0_LOAD_S (0)
#define SYSTIMER_UNIT0_LOAD_TIMER_UNIT0_LOAD_V(v) (((v) << 0) & 0x00000001U)

// system timer unit1 conf sync register
#define SYSTIMER_UNIT1_LOAD_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x60))
#define SYSTIMER_UNIT1_LOAD_TIMER_UNIT1_LOAD_M (0x00000001U)
#define SYSTIMER_UNIT1_LOAD_TIMER_UNIT1_LOAD_S (0)
#define SYSTIMER_UNIT1_LOAD_TIMER_UNIT1_LOAD_V(v) (((v) << 0) & 0x00000001U)

// systimer interrupt enable register
#define SYSTIMER_INT_ENA_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x64))
#define SYSTIMER_INT_ENA_TARGET0_INT_ENA_M (0x00000001U)
#define SYSTIMER_INT_ENA_TARGET0_INT_ENA_S (0)
#define SYSTIMER_INT_ENA_TARGET0_INT_ENA_V(v) (((v) << 0) & 0x00000001U)
#define SYSTIMER_INT_ENA_TARGET1_INT_ENA_M (0x00000002U)
#define SYSTIMER_INT_ENA_TARGET1_INT_ENA_S (1)
#define SYSTIMER_INT_ENA_TARGET1_INT_ENA_V(v) (((v) << 1) & 0x00000002U)
#define SYSTIMER_INT_ENA_TARGET2_INT_ENA_M (0x00000004U)
#define SYSTIMER_INT_ENA_TARGET2_INT_ENA_S (2)
#define SYSTIMER_INT_ENA_TARGET2_INT_ENA_V(v) (((v) << 2) & 0x00000004U)

// systimer interrupt raw register
#define SYSTIMER_INT_RAW_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x68))
#define SYSTIMER_INT_RAW_TARGET0_INT_RAW_M (0x00000001U)
#define SYSTIMER_INT_RAW_TARGET0_INT_RAW_S (0)
#define SYSTIMER_INT_RAW_TARGET0_INT_RAW_V(v) (((v) << 0) & 0x00000001U)
#define SYSTIMER_INT_RAW_TARGET1_INT_RAW_M (0x00000002U)
#define SYSTIMER_INT_RAW_TARGET1_INT_RAW_S (1)
#define SYSTIMER_INT_RAW_TARGET1_INT_RAW_V(v) (((v) << 1) & 0x00000002U)
#define SYSTIMER_INT_RAW_TARGET2_INT_RAW_M (0x00000004U)
#define SYSTIMER_INT_RAW_TARGET2_INT_RAW_S (2)
#define SYSTIMER_INT_RAW_TARGET2_INT_RAW_V(v) (((v) << 2) & 0x00000004U)

// systimer interrupt clear register
#define SYSTIMER_INT_CLR_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x6C))
#define SYSTIMER_INT_CLR_TARGET0_INT_CLR_M (0x00000001U)
#define SYSTIMER_INT_CLR_TARGET0_INT_CLR_S (0)
#define SYSTIMER_INT_CLR_TARGET0_INT_CLR_V(v) (((v) << 0) & 0x00000001U)
#define SYSTIMER_INT_CLR_TARGET1_INT_CLR_M (0x00000002U)
#define SYSTIMER_INT_CLR_TARGET1_INT_CLR_S (1)
#define SYSTIMER_INT_CLR_TARGET1_INT_CLR_V(v) (((v) << 1) & 0x00000002U)
#define SYSTIMER_INT_CLR_TARGET2_INT_CLR_M (0x00000004U)
#define SYSTIMER_INT_CLR_TARGET2_INT_CLR_S (2)
#define SYSTIMER_INT_CLR_TARGET2_INT_CLR_V(v) (((v) << 2) & 0x00000004U)

// systimer interrupt status register
#define SYSTIMER_INT_ST_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x70))
#define SYSTIMER_INT_ST_TARGET0_INT_ST_M (0x00000001U)
#define SYSTIMER_INT_ST_TARGET0_INT_ST_S (0)
#define SYSTIMER_INT_ST_TARGET0_INT_ST_V(v) (((v) << 0) & 0x00000001U)
#define SYSTIMER_INT_ST_TARGET1_INT_ST_M (0x00000002U)
#define SYSTIMER_INT_ST_TARGET1_INT_ST_S (1)
#define SYSTIMER_INT_ST_TARGET1_INT_ST_V(v) (((v) << 1) & 0x00000002U)
#define SYSTIMER_INT_ST_TARGET2_INT_ST_M (0x00000004U)
#define SYSTIMER_INT_ST_TARGET2_INT_ST_S (2)
#define SYSTIMER_INT_ST_TARGET2_INT_ST_V(v) (((v) << 2) & 0x00000004U)

// system timer comp0 actual target value low register
#define SYSTIMER_REAL_TARGET0_LO_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x74))
#define SYSTIMER_REAL_TARGET0_LO_TARGET0_LO_RO_M (0xFFFFFFFFU)
#define SYSTIMER_REAL_TARGET0_LO_TARGET0_LO_RO_S (0)
#define SYSTIMER_REAL_TARGET0_LO_TARGET0_LO_RO_V(v) (((v) << 0) & 0xFFFFFFFFU)

// system timer comp0 actual target value high register
#define SYSTIMER_REAL_TARGET0_HI_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x78))
#define SYSTIMER_REAL_TARGET0_HI_TARGET0_HI_RO_M (0x000FFFFFU)
#define SYSTIMER_REAL_TARGET0_HI_TARGET0_HI_RO_S (0)
#define SYSTIMER_REAL_TARGET0_HI_TARGET0_HI_RO_V(v) (((v) << 0) & 0x000FFFFFU)

// system timer comp1 actual target value low register
#define SYSTIMER_REAL_TARGET1_LO_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x7C))
#define SYSTIMER_REAL_TARGET1_LO_TARGET1_LO_RO_M (0xFFFFFFFFU)
#define SYSTIMER_REAL_TARGET1_LO_TARGET1_LO_RO_S (0)
#define SYSTIMER_REAL_TARGET1_LO_TARGET1_LO_RO_V(v) (((v) << 0) & 0xFFFFFFFFU)

// system timer comp1 actual target value high register
#define SYSTIMER_REAL_TARGET1_HI_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x80))
#define SYSTIMER_REAL_TARGET1_HI_TARGET1_HI_RO_M (0x000FFFFFU)
#define SYSTIMER_REAL_TARGET1_HI_TARGET1_HI_RO_S (0)
#define SYSTIMER_REAL_TARGET1_HI_TARGET1_HI_RO_V(v) (((v) << 0) & 0x000FFFFFU)

// system timer comp2 actual target value low register
#define SYSTIMER_REAL_TARGET2_LO_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x84))
#define SYSTIMER_REAL_TARGET2_LO_TARGET2_LO_RO_M (0xFFFFFFFFU)
#define SYSTIMER_REAL_TARGET2_LO_TARGET2_LO_RO_S (0)
#define SYSTIMER_REAL_TARGET2_LO_TARGET2_LO_RO_V(v) (((v) << 0) & 0xFFFFFFFFU)

// system timer comp2 actual target value high register
#define SYSTIMER_REAL_TARGET2_HI_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0x88))
#define SYSTIMER_REAL_TARGET2_HI_TARGET2_HI_RO_M (0x000FFFFFU)
#define SYSTIMER_REAL_TARGET2_HI_TARGET2_HI_RO_S (0)
#define SYSTIMER_REAL_TARGET2_HI_TARGET2_HI_RO_V(v) (((v) << 0) & 0x000FFFFFU)

// system timer version control register
#define SYSTIMER_DATE_REG ((volatile uint32_t *)(SYSTIMER_BASE + 0xFC))
#define SYSTIMER_DATE_DATE_M (0xFFFFFFFFU)
#define SYSTIMER_DATE_DATE_S (0)
#define SYSTIMER_DATE_DATE_V(v) (((v) << 0) & 0xFFFFFFFFU)

#endif // SYSTIMER_H
