/*
 * TRACE.h
 * RISC-V Trace Encoder
 * Base Address: 0x600C0000
 */

#ifndef TRACE_H
#define TRACE_H

#include <stdint.h>

#define TRACE_BASE 0x600C0000

// mem start addr
#define TRACE_MEM_START_ADDR_REG ((volatile uint32_t *)(TRACE_BASE + 0x0))
#define TRACE_MEM_START_ADDR_MEM_START_ADDR_M (0xFFFFFFFFU)
#define TRACE_MEM_START_ADDR_MEM_START_ADDR_S (0)
#define TRACE_MEM_START_ADDR_MEM_START_ADDR_V(v) (((v) << 0) & 0xFFFFFFFFU)

// mem end addr
#define TRACE_MEM_END_ADDR_REG ((volatile uint32_t *)(TRACE_BASE + 0x4))
#define TRACE_MEM_END_ADDR_MEM_END_ADDR_M (0xFFFFFFFFU)
#define TRACE_MEM_END_ADDR_MEM_END_ADDR_S (0)
#define TRACE_MEM_END_ADDR_MEM_END_ADDR_V(v) (((v) << 0) & 0xFFFFFFFFU)

// mem current addr
#define TRACE_MEM_CURRENT_ADDR_REG ((volatile uint32_t *)(TRACE_BASE + 0x8))
#define TRACE_MEM_CURRENT_ADDR_MEM_CURRENT_ADDR_M (0xFFFFFFFFU)
#define TRACE_MEM_CURRENT_ADDR_MEM_CURRENT_ADDR_S (0)
#define TRACE_MEM_CURRENT_ADDR_MEM_CURRENT_ADDR_V(v) (((v) << 0) & 0xFFFFFFFFU)

// mem addr update
#define TRACE_MEM_ADDR_UPDATE_REG ((volatile uint32_t *)(TRACE_BASE + 0xC))
#define TRACE_MEM_ADDR_UPDATE_MEM_CURRENT_ADDR_UPDATE_M (0x00000001U)
#define TRACE_MEM_ADDR_UPDATE_MEM_CURRENT_ADDR_UPDATE_S (0)
#define TRACE_MEM_ADDR_UPDATE_MEM_CURRENT_ADDR_UPDATE_V(v) (((v) << 0) & 0x00000001U)

// fifo status register
#define TRACE_FIFO_STATUS_REG ((volatile uint32_t *)(TRACE_BASE + 0x10))
#define TRACE_FIFO_STATUS_FIFO_EMPTY_M (0x00000001U)
#define TRACE_FIFO_STATUS_FIFO_EMPTY_S (0)
#define TRACE_FIFO_STATUS_FIFO_EMPTY_V(v) (((v) << 0) & 0x00000001U)
#define TRACE_FIFO_STATUS_WORK_STATUS_M (0x00000002U)
#define TRACE_FIFO_STATUS_WORK_STATUS_S (1)
#define TRACE_FIFO_STATUS_WORK_STATUS_V(v) (((v) << 1) & 0x00000002U)

// interrupt enable register
#define TRACE_INTR_ENA_REG ((volatile uint32_t *)(TRACE_BASE + 0x14))
#define TRACE_INTR_ENA_FIFO_OVERFLOW_INTR_ENA_M (0x00000001U)
#define TRACE_INTR_ENA_FIFO_OVERFLOW_INTR_ENA_S (0)
#define TRACE_INTR_ENA_FIFO_OVERFLOW_INTR_ENA_V(v) (((v) << 0) & 0x00000001U)
#define TRACE_INTR_ENA_MEM_FULL_INTR_ENA_M (0x00000002U)
#define TRACE_INTR_ENA_MEM_FULL_INTR_ENA_S (1)
#define TRACE_INTR_ENA_MEM_FULL_INTR_ENA_V(v) (((v) << 1) & 0x00000002U)

// interrupt status register
#define TRACE_INTR_RAW_REG ((volatile uint32_t *)(TRACE_BASE + 0x18))
#define TRACE_INTR_RAW_FIFO_OVERFLOW_INTR_RAW_M (0x00000001U)
#define TRACE_INTR_RAW_FIFO_OVERFLOW_INTR_RAW_S (0)
#define TRACE_INTR_RAW_FIFO_OVERFLOW_INTR_RAW_V(v) (((v) << 0) & 0x00000001U)
#define TRACE_INTR_RAW_MEM_FULL_INTR_RAW_M (0x00000002U)
#define TRACE_INTR_RAW_MEM_FULL_INTR_RAW_S (1)
#define TRACE_INTR_RAW_MEM_FULL_INTR_RAW_V(v) (((v) << 1) & 0x00000002U)

// interrupt clear register
#define TRACE_INTR_CLR_REG ((volatile uint32_t *)(TRACE_BASE + 0x1C))
#define TRACE_INTR_CLR_FIFO_OVERFLOW_INTR_CLR_M (0x00000001U)
#define TRACE_INTR_CLR_FIFO_OVERFLOW_INTR_CLR_S (0)
#define TRACE_INTR_CLR_FIFO_OVERFLOW_INTR_CLR_V(v) (((v) << 0) & 0x00000001U)
#define TRACE_INTR_CLR_MEM_FULL_INTR_CLR_M (0x00000002U)
#define TRACE_INTR_CLR_MEM_FULL_INTR_CLR_S (1)
#define TRACE_INTR_CLR_MEM_FULL_INTR_CLR_V(v) (((v) << 1) & 0x00000002U)

// trigger register
#define TRACE_TRIGGER_REG ((volatile uint32_t *)(TRACE_BASE + 0x20))
#define TRACE_TRIGGER_ON_M (0x00000001U)
#define TRACE_TRIGGER_ON_S (0)
#define TRACE_TRIGGER_ON_V(v) (((v) << 0) & 0x00000001U)
#define TRACE_TRIGGER_OFF_M (0x00000002U)
#define TRACE_TRIGGER_OFF_S (1)
#define TRACE_TRIGGER_OFF_V(v) (((v) << 1) & 0x00000002U)
#define TRACE_TRIGGER_MEM_LOOP_M (0x00000004U)
#define TRACE_TRIGGER_MEM_LOOP_S (2)
#define TRACE_TRIGGER_MEM_LOOP_V(v) (((v) << 2) & 0x00000004U)
#define TRACE_TRIGGER_RESTART_ENA_M (0x00000008U)
#define TRACE_TRIGGER_RESTART_ENA_S (3)
#define TRACE_TRIGGER_RESTART_ENA_V(v) (((v) << 3) & 0x00000008U)

// resync configuration register
#define TRACE_RESYNC_PROLONGED_REG ((volatile uint32_t *)(TRACE_BASE + 0x24))
#define TRACE_RESYNC_PROLONGED_RESYNC_PROLONGED_M (0x00FFFFFFU)
#define TRACE_RESYNC_PROLONGED_RESYNC_PROLONGED_S (0)
#define TRACE_RESYNC_PROLONGED_RESYNC_PROLONGED_V(v) (((v) << 0) & 0x00FFFFFFU)
#define TRACE_RESYNC_PROLONGED_RESYNC_MODE_M (0x01000000U)
#define TRACE_RESYNC_PROLONGED_RESYNC_MODE_S (24)
#define TRACE_RESYNC_PROLONGED_RESYNC_MODE_V(v) (((v) << 24) & 0x01000000U)

// Clock gate control register
#define TRACE_CLOCK_GATE_REG ((volatile uint32_t *)(TRACE_BASE + 0x28))
#define TRACE_CLOCK_GATE_CLK_EN_M (0x00000001U)
#define TRACE_CLOCK_GATE_CLK_EN_S (0)
#define TRACE_CLOCK_GATE_CLK_EN_V(v) (((v) << 0) & 0x00000001U)

// Version control register
#define TRACE_DATE_REG ((volatile uint32_t *)(TRACE_BASE + 0x3FC))
#define TRACE_DATE_DATE_M (0x0FFFFFFFU)
#define TRACE_DATE_DATE_S (0)
#define TRACE_DATE_DATE_V(v) (((v) << 0) & 0x0FFFFFFFU)

#endif // TRACE_H
