#!/usr/bin/env python3
"""Turns web/index.html (the light page, REV-25) into the gzip-compressed C array served at /.

usage: gen_web.py <page.html> <output header>
       gen_web.py --self-test <page.html>

Minify (conservative, the browser gets the same page): HTML comments, indentation, blank lines and
full-line `//` comments in the script are removed; CSS whitespace around punctuation is collapsed.
Script line breaks stay (automatic semicolon insertion). The page therefore keeps script comments on
lines of their own and has no multi-line strings and no strings in the CSS.
Then gzip -9 with a zero timestamp, so the output is reproducible. The header is rewritten only when its
content changes.

The self-test checks the minifier and the page rules: no timers (REV-15: the page never polls), only
REST v1 paths, and the size budget from src/http_server.h (headers + page in one response buffer).
"""
import gzip
import os
import re
import sys

SRC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src')
BYTES_PER_ROW = 16
ALLOWED_API = {'/api/v1/'}          # the page builds /api/v1/light and /api/v1/device from this prefix
FORBIDDEN = ('setTimeout', 'setInterval')


def collapse_css(css):
    css = re.sub(r'\s*([{}:;,>])\s*', r'\1', css)
    return css.replace(';}', '}').strip()


def minify(html):
    html = re.sub(r'<!--.*?-->\s*', '', html, flags=re.S)
    html = re.sub(r'<style>(.*?)</style>', lambda m: '<style>' + collapse_css(m.group(1)) + '</style>',
                  html, flags=re.S)
    lines, in_script = [], False
    for raw in html.split('\n'):
        line = raw.strip()
        if not line or (in_script and line.startswith('//')):
            continue
        if line == '<script>':
            in_script = True
        elif line == '</script>':
            in_script = False
        lines.append(line)
    return '\n'.join(lines) + '\n'


def compress(page_text):
    return gzip.compress(minify(page_text).encode('utf-8'), compresslevel=9, mtime=0)


def render(gz, raw_len):
    rows = ['    ' + ', '.join('0x%02X' % b for b in gz[i:i + BYTES_PER_ROW]) + ','
            for i in range(0, len(gz), BYTES_PER_ROW)]
    return '\n'.join([
        '/* Generated by scripts/gen_web.py from web/index.html: do not edit. */',
        '#ifndef IRON_V_WEB_INDEX_GZ_H',
        '#define IRON_V_WEB_INDEX_GZ_H',
        '',
        '#include <stdint.h>',
        '#include "section.h"',
        '',
        '#define WEB_INDEX_RAW_LEN  %uU   /* minified page before gzip */' % raw_len,
        '#define WEB_INDEX_GZ_LEN   %uU' % len(gz),
        '',
        'static const uint8_t g_web_index_gz[WEB_INDEX_GZ_LEN] FLASH_RODATA_ATTR = {',
    ] + rows + ['};', '', '#endif', ''])


def write_if_changed(path, content):
    try:
        with open(path) as f:
            if f.read() == content:
                return False
    except OSError:
        pass
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    with open(path, 'w') as f:
        f.write(content)
    return True


def header_define(name):
    with open(os.path.join(SRC_DIR, 'http_server.h')) as f:
        m = re.search(r'#define\s+%s\s+(\d+)U' % name, f.read())
    assert m, '%s not found in src/http_server.h' % name
    return int(m.group(1))


def self_test(page_path):
    assert minify('<!-- a\nb -->\n  <p>x</p>\n\n') == '<p>x</p>\n'
    assert minify('<style>\n  a , b > c { color : red ; margin: 0 auto; }\n</style>\n') == \
        '<style>a,b>c{color:red;margin:0 auto}</style>\n'
    js = '<script>\n  // note\n  const u = "http://x";  // kept\n  f()\n  g()\n</script>\n'
    assert minify(js) == '<script>\nconst u = "http://x";  // kept\nf()\ng()\n</script>\n', minify(js)
    assert minify('<p>\n// not a script comment\n</p>\n') == '<p>\n// not a script comment\n</p>\n'
    assert compress('<p>x</p>') == compress('<p>x</p>'), 'gzip output must be reproducible'

    with open(page_path, encoding='utf-8') as f:
        page = f.read()
    for name in FORBIDDEN:
        assert name not in page, 'page uses %s (REV-15: no timers, no polling)' % name
    apis = set(re.findall(r'/api/[A-Za-z0-9_/]*', page))
    assert apis and apis <= ALLOWED_API, 'page uses other API paths than REST v1: %s' % sorted(apis - ALLOWED_API)
    small = minify(page)
    gz = compress(page)
    assert gzip.decompress(gz).decode('utf-8') == small, 'gzip round trip'
    budget = header_define('HTTP_RESPONSE_BUF_SIZE') - header_define('HTTP_HEADER_RESERVE')
    assert len(gz) <= budget, 'page is %u B compressed, budget %u B' % (len(gz), budget)
    print('gen_web self-test: OK (page %u B, minified %u B, gzip %u B of %u B)'
          % (len(page.encode('utf-8')), len(small.encode('utf-8')), len(gz), budget))


def main(argv):
    if len(argv) == 3 and argv[1] == '--self-test':
        self_test(argv[2])
        return 0
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    src, out = argv[1], argv[2]
    with open(src, encoding='utf-8') as f:
        page = f.read()
    gz = compress(page)
    write_if_changed(out, render(gz, len(minify(page).encode('utf-8'))))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
