/*
 * src/config.h
 *
 * Iron V System & Subsystem Configuration Manifest
 *
 * Centralizes all user-configurable parameters for networking, wireless PHY,
 * device identification, system telemetry intervals, and console defaults.
 *
 * Execution Standards (AGENTS.md):
 * - Safe abstraction: Hardware invariants (clock trees, PLL dividers, memory cartography,
 *   PMP boundaries) are strictly protected in their architectural driver blocks and
 *   MUST NOT be exposed here to prevent operational disruption.
 * - Non-zero symbolic definitions: All items use strongly-typed uppercase macros
 *   with #ifndef guards, permitting compile-time overrides via CFLAGS.
 * - Local overrides: the untracked .config (see config.example) becomes config_gen.h
 *   (build/gen/, generated by scripts/gen_config.py); its values win over the defaults below.
 */

#ifndef IRON_V_CONFIG_H
#define IRON_V_CONFIG_H

#include <stdint.h>
#include "config_gen.h"   /* local .config overrides (build/gen; tests/host stub for host tests) */

/* ========================================================================= */
/* 1. Device Identification & System Metadata                                */
/* ========================================================================= */

#ifndef CONFIG_DEVICE_HOSTNAME
#define CONFIG_DEVICE_HOSTNAME              "iron-v"
#endif

#ifndef CONFIG_DEVICE_MANUFACTURER
#define CONFIG_DEVICE_MANUFACTURER          "Iron-V RISC-V Team"
#endif

#ifndef CONFIG_DEVICE_MODEL_NUMBER
#define CONFIG_DEVICE_MODEL_NUMBER          "ESP32-C6-BareMetal"
#endif

#ifndef CONFIG_FIRMWARE_REVISION
#define CONFIG_FIRMWARE_REVISION            "1.0.0"
#endif

#ifndef CONFIG_HARDWARE_REVISION
#define CONFIG_HARDWARE_REVISION            "ESP32-C6-WROOM-1"
#endif

/* ========================================================================= */
/* 2. IPv4 Network Subsystem Defaults (RFC 791 / RFC 826)                    */
/* ========================================================================= */

#ifndef CONFIG_NET_IP_OCTET_1
#define CONFIG_NET_IP_OCTET_1               192U
#endif
#ifndef CONFIG_NET_IP_OCTET_2
#define CONFIG_NET_IP_OCTET_2               168U
#endif
#ifndef CONFIG_NET_IP_OCTET_3
#define CONFIG_NET_IP_OCTET_3               1U
#endif
#ifndef CONFIG_NET_IP_OCTET_4
#define CONFIG_NET_IP_OCTET_4               1U
#endif

#ifndef CONFIG_NET_NETMASK_OCTET_1
#define CONFIG_NET_NETMASK_OCTET_1          255U
#endif
#ifndef CONFIG_NET_NETMASK_OCTET_2
#define CONFIG_NET_NETMASK_OCTET_2          255U
#endif
#ifndef CONFIG_NET_NETMASK_OCTET_3
#define CONFIG_NET_NETMASK_OCTET_3          255U
#endif
#ifndef CONFIG_NET_NETMASK_OCTET_4
#define CONFIG_NET_NETMASK_OCTET_4          0U
#endif

#ifndef CONFIG_NET_GATEWAY_OCTET_1
#define CONFIG_NET_GATEWAY_OCTET_1          192U
#endif
#ifndef CONFIG_NET_GATEWAY_OCTET_2
#define CONFIG_NET_GATEWAY_OCTET_2          168U
#endif
#ifndef CONFIG_NET_GATEWAY_OCTET_3
#define CONFIG_NET_GATEWAY_OCTET_3          1U
#endif
#ifndef CONFIG_NET_GATEWAY_OCTET_4
#define CONFIG_NET_GATEWAY_OCTET_4          1U
#endif

#ifndef CONFIG_NET_DNS_OCTET_1
#define CONFIG_NET_DNS_OCTET_1              192U
#endif
#ifndef CONFIG_NET_DNS_OCTET_2
#define CONFIG_NET_DNS_OCTET_2              168U
#endif
#ifndef CONFIG_NET_DNS_OCTET_3
#define CONFIG_NET_DNS_OCTET_3              1U
#endif
#ifndef CONFIG_NET_DNS_OCTET_4
#define CONFIG_NET_DNS_OCTET_4              1U
#endif

/* Convenience IPv4 Address Packing Macro */
#define CONFIG_IP4_ADDR(a, b, c, d) \
    ((uint32_t)((((uint32_t)(a) & 0xFFU) << 24U) | \
                (((uint32_t)(b) & 0xFFU) << 16U) | \
                (((uint32_t)(c) & 0xFFU) << 8U)  | \
                ((uint32_t)(d) & 0xFFU)))

#ifndef CONFIG_NET_DEFAULT_IP
#define CONFIG_NET_DEFAULT_IP \
    CONFIG_IP4_ADDR(CONFIG_NET_IP_OCTET_1, CONFIG_NET_IP_OCTET_2, CONFIG_NET_IP_OCTET_3, CONFIG_NET_IP_OCTET_4)
#endif

#ifndef CONFIG_NET_DEFAULT_NETMASK
#define CONFIG_NET_DEFAULT_NETMASK \
    CONFIG_IP4_ADDR(CONFIG_NET_NETMASK_OCTET_1, CONFIG_NET_NETMASK_OCTET_2, CONFIG_NET_NETMASK_OCTET_3, CONFIG_NET_NETMASK_OCTET_4)
#endif

#ifndef CONFIG_NET_DEFAULT_GATEWAY
#define CONFIG_NET_DEFAULT_GATEWAY \
    CONFIG_IP4_ADDR(CONFIG_NET_GATEWAY_OCTET_1, CONFIG_NET_GATEWAY_OCTET_2, CONFIG_NET_GATEWAY_OCTET_3, CONFIG_NET_GATEWAY_OCTET_4)
#endif

#ifndef CONFIG_NET_DEFAULT_DNS
#define CONFIG_NET_DEFAULT_DNS \
    CONFIG_IP4_ADDR(CONFIG_NET_DNS_OCTET_1, CONFIG_NET_DNS_OCTET_2, CONFIG_NET_DNS_OCTET_3, CONFIG_NET_DNS_OCTET_4)
#endif

#ifndef CONFIG_NET_DEFAULT_TTL
#define CONFIG_NET_DEFAULT_TTL              64U
#endif

/* ========================================================================= */
/* 3. TCP Protocol Engine Defaults (RFC 793)                                 */
/* ========================================================================= */

#ifndef CONFIG_TCP_DEFAULT_WINDOW
#define CONFIG_TCP_DEFAULT_WINDOW           1024U
#endif

#ifndef CONFIG_TCP_DEFAULT_MSS
#define CONFIG_TCP_DEFAULT_MSS              1460U
#endif

#ifndef CONFIG_TCP_RETRANSMIT_TIMEOUT_MS
#define CONFIG_TCP_RETRANSMIT_TIMEOUT_MS    1000U
#endif

/* Retransmissions of one data/FIN segment before the connection is dropped (RTO doubles each time:
 * 6 rides out ~2 min of loss, REV-13) */
#ifndef CONFIG_TCP_MAX_RETRIES
#define CONFIG_TCP_MAX_RETRIES              6U
#endif

#ifndef CONFIG_TCP_DEFAULT_HTTP_PORT
#define CONFIG_TCP_DEFAULT_HTTP_PORT        80U
#endif

/* ========================================================================= */
/* 4. Wi-Fi 6 (802.11ax) MAC & Station Defaults                              */
/* ========================================================================= */

/* Setup SoftAP (open; started at boot only while no station credentials are saved,
 * otherwise only by the setup button) */
#ifndef CONFIG_WIFI_AP_SSID
#define CONFIG_WIFI_AP_SSID                 "IronV-AP"
#endif

#ifndef CONFIG_WIFI_AP_CHANNEL
#define CONFIG_WIFI_AP_CHANNEL              1U
#endif

/* Station network seeded into NVS on the first boot without saved credentials (REV-30).
 * Empty by default: images built without a .config carry no credentials. */
#ifndef CONFIG_WIFI_STA_SSID
#define CONFIG_WIFI_STA_SSID                ""
#endif

#ifndef CONFIG_WIFI_STA_PASSPHRASE
#define CONFIG_WIFI_STA_PASSPHRASE          ""
#endif

#ifndef CONFIG_WIFI_COUNTRY_CODE
#define CONFIG_WIFI_COUNTRY_CODE            "US"
#endif

#ifndef CONFIG_WIFI_MAX_TX_POWER_DBM
#define CONFIG_WIFI_MAX_TX_POWER_DBM        20U
#endif

#ifndef CONFIG_WIFI_USE_STATIC_IP
#define CONFIG_WIFI_USE_STATIC_IP           1U
#endif

#ifndef CONFIG_WIFI_AUTO_START_AP
#define CONFIG_WIFI_AUTO_START_AP           1U
#endif

/* Setup button (REV-15): holding it opens the setup SoftAP on a provisioned board (BOOT = GPIO9).
 * The SoftAP closes once no client has been connected for the idle timeout, or at the maximum. */
#ifndef CONFIG_SETUP_BUTTON_GPIO
#define CONFIG_SETUP_BUTTON_GPIO            9U
#endif

/* Light (REV-23): the DevKitC-1's addressable RGB LED (WS2812-class) on GPIO8, driven by RMT */
#ifndef CONFIG_LIGHT_LED_GPIO
#define CONFIG_LIGHT_LED_GPIO               8U
#endif

#ifndef CONFIG_SETUP_AP_IDLE_TIMEOUT_S
#define CONFIG_SETUP_AP_IDLE_TIMEOUT_S      600U
#endif

#ifndef CONFIG_SETUP_AP_MAX_S
#define CONFIG_SETUP_AP_MAX_S               1800U
#endif

/* Setup SoftAP captive portal. DHCP always advertises the board as gateway + DNS,
 * so the phone routes through the SoftAP (a gateway-less lease leaves Android on
 * mobile data and 192.168.1.1 unreachable).
 * 1 (default, phone-verified): captive portal - catch-all DNS + probe redirect pop the
 *    "sign in" page; Android leaves the network once that page has been idle ~20 s.
 * 0 (not yet phone-verified): "no internet" network - DNS answers only the board's own
 *    names (NXDOMAIN otherwise) and probes get 404, so the phone should report
 *    "no internet" and offer to stay connected; the user opens /setup manually. */
#ifndef CONFIG_SOFTAP_CAPTIVE_PORTAL
#define CONFIG_SOFTAP_CAPTIVE_PORTAL        1U
#endif

/* ========================================================================= */
/* 5. IEEE 802.15.4 (Zigbee / Thread) Transceiver Defaults                   */
/* ========================================================================= */

#ifndef CONFIG_IEEE802154_DEFAULT_CHANNEL
#define CONFIG_IEEE802154_DEFAULT_CHANNEL   15U
#endif

#ifndef CONFIG_IEEE802154_DEFAULT_PAN_ID
#define CONFIG_IEEE802154_DEFAULT_PAN_ID    0x1A2BU
#endif

#ifndef CONFIG_IEEE802154_DEFAULT_SHORT_ADDR
#define CONFIG_IEEE802154_DEFAULT_SHORT_ADDR 0x1234U
#endif

#ifndef CONFIG_IEEE802154_DEFAULT_TX_POWER
#define CONFIG_IEEE802154_DEFAULT_TX_POWER  0x0FU
#endif

#ifndef CONFIG_IEEE802154_AUTO_ACK_TX
#define CONFIG_IEEE802154_AUTO_ACK_TX       1U
#endif

#ifndef CONFIG_IEEE802154_AUTO_ACK_RX
#define CONFIG_IEEE802154_AUTO_ACK_RX       1U
#endif

/* ========================================================================= */
/* 6. System Heartbeat & Interactive Shell Defaults                          */
/* ========================================================================= */

#ifndef CONFIG_SYSTEM_HEARTBEAT_INTERVAL_SEC
#define CONFIG_SYSTEM_HEARTBEAT_INTERVAL_SEC 10U
#endif

#ifndef CONFIG_CONSOLE_PROMPT
#define CONFIG_CONSOLE_PROMPT               "iron_v> "
#endif

#ifndef CONFIG_CONSOLE_DEFAULT_ECHO
#define CONFIG_CONSOLE_DEFAULT_ECHO         1U
#endif

#endif /* IRON_V_CONFIG_H */
