/*
 * src/wifi_regulatory.c
 *
 * Iron V Bare-Metal Wi-Fi 6 Regulatory Domain & Channel Geometry Implementation
 *
 * Design Choice Attribution:
 * 802.11 regulatory channel boundaries, bandwidth limits, EIRP power constraints,
 * and regulatory domain country-code mapping structures adapted from Espressif Systems'
 * ESP-IDF Wi-Fi regulatory model (components/esp_wifi/src/esp_wifi_regulatory.c).
 *
 * Conforms to Iron V Project Standards:
 * - Zero magic numbers: uses defined constants from wifi_regulatory.h
 * - Static flash/ROM allocation only: zero dynamic heap usage
 * - Clean compilation: -Wall -Wextra -Werror compliant
 */

#include "wifi_regulatory.h"

/*
 * Country Code Mapping Table (regdomain_table)
 * Linked directly by Espressif libnet80211.a (ieee80211_regdomain.o).
 * Maps 2-character ISO 3166-1 alpha-2 country codes to regulatory profile indices.
 * Terminated by sentinel string "##".
 */
const wifi_regdomain_t regdomain_table[] = {
    {"01", ESP_WIFI_REGULATORY_TYPE_DEFAULT},
    {"EU", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"AD", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"AE", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"AF", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"AI", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"AL", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"AM", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"AN", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"AR", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"AS", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"AT", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"AU", ESP_WIFI_REGULATORY_TYPE_RCM},
    {"AW", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"AZ", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BA", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BB", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BD", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BE", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BF", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BG", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BH", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BL", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BM", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"BN", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BO", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BR", ESP_WIFI_REGULATORY_TYPE_NCC},
    {"BS", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BT", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BW", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BY", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"BZ", ESP_WIFI_REGULATORY_TYPE_NCC},
    {"CA", ESP_WIFI_REGULATORY_TYPE_RCM},
    {"CF", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"CH", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"CI", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"CL", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"CN", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"CO", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"CR", ESP_WIFI_REGULATORY_TYPE_RCM},
    {"CU", ESP_WIFI_REGULATORY_TYPE_KCC},
    {"CX", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"CY", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"CZ", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"DE", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"DK", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"DM", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"DO", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"DZ", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"EC", ESP_WIFI_REGULATORY_TYPE_NCC},
    {"EE", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"EG", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"ES", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"ET", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"FI", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"FM", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"FO", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"FR", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"GB", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"GD", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"GE", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"GF", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"GH", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"GI", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"GL", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"GP", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"GR", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"GT", ESP_WIFI_REGULATORY_TYPE_GT},
    {"GU", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"GY", ESP_WIFI_REGULATORY_TYPE_NCC},
    {"HK", ESP_WIFI_REGULATORY_TYPE_RCM},
    {"HN", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"HR", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"HT", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"HU", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"ID", ESP_WIFI_REGULATORY_TYPE_GT},
    {"IE", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"IL", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"IM", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"IN", ESP_WIFI_REGULATORY_TYPE_NCC},
    {"IR", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"IS", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"IT", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"JM", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"JO", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"JP", ESP_WIFI_REGULATORY_TYPE_MIC},
    {"KE", ESP_WIFI_REGULATORY_TYPE_KE},
    {"KH", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"KN", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"KP", ESP_WIFI_REGULATORY_TYPE_KP},
    {"KR", ESP_WIFI_REGULATORY_TYPE_KCC},
    {"KW", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"KY", ESP_WIFI_REGULATORY_TYPE_NCC},
    {"KZ", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"LB", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"LC", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"LI", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"LK", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"LS", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"LT", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"LU", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"LV", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MA", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MC", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MD", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"ME", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MF", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MH", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"MK", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MN", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MO", ESP_WIFI_REGULATORY_TYPE_KCC},
    {"MP", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"MQ", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MR", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MT", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MU", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MV", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MW", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MX", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"MY", ESP_WIFI_REGULATORY_TYPE_MY},
    {"NA", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"NG", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"NI", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"NL", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"NO", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"NP", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"NZ", ESP_WIFI_REGULATORY_TYPE_RCM},
    {"OM", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"PA", ESP_WIFI_REGULATORY_TYPE_RCM},
    {"PE", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"PF", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"PG", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"PH", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"PK", ESP_WIFI_REGULATORY_TYPE_PK},
    {"PL", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"PM", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"PR", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"PT", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"PW", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"PY", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"QA", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"RE", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"RO", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"RS", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"RU", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"RW", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"SA", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"SE", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"SG", ESP_WIFI_REGULATORY_TYPE_KCC},
    {"SI", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"SK", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"SM", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"SN", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"SR", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"SV", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"SX", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"SY", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"TC", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"TD", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"TG", ESP_WIFI_REGULATORY_TYPE_TG},
    {"TH", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"TN", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"TR", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"TT", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"TW", ESP_WIFI_REGULATORY_TYPE_NCC},
    {"TZ", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"UA", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"UG", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"US", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"UY", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"UZ", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"VA", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"VC", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"VE", ESP_WIFI_REGULATORY_TYPE_NCC},
    {"VI", ESP_WIFI_REGULATORY_TYPE_FCC},
    {"VN", ESP_WIFI_REGULATORY_TYPE_KCC},
    {"VU", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"WF", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"WS", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"YE", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"YT", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"ZA", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"ZW", ESP_WIFI_REGULATORY_TYPE_IFETEL},
    {"##", ESP_WIFI_REGULATORY_TYPE_MAX}, /* Sentinel indicating end of table */
};

/*
 * Regulatory Channel & EIRP Rule Profiles (regulatory_data)
 * Linked directly by Espressif libnet80211.a (ieee80211_regdomain.o).
 * Provides maximum transmit power, channel span, and bandwidth constraints.
 */
const wifi_regulatory_t regulatory_data[] = {
    /* [0] ESP_WIFI_REGULATORY_TYPE_DEFAULT: Channels 1-11, 40MHz, 20dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_11, WIFI_REG_BW_40M, WIFI_REG_EIRP_20DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [1] ESP_WIFI_REGULATORY_TYPE_CE: Channels 1-13, 40MHz, 20dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_20DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [2] ESP_WIFI_REGULATORY_TYPE_ACMA: Channels 1-13, 40MHz, 36dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_36DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [3] ESP_WIFI_REGULATORY_TYPE_ANATEL: Channels 1-13, 40MHz, 30dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_30DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [4] ESP_WIFI_REGULATORY_TYPE_ISED: Channels 1-13, 40MHz, 36dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_36DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [5] ESP_WIFI_REGULATORY_TYPE_SRRC: Channels 1-13, 40MHz, 20dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_20DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [6] ESP_WIFI_REGULATORY_TYPE_OFCA: Channels 1-13, 40MHz, 36dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_36DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [7] ESP_WIFI_REGULATORY_TYPE_WPC: Channels 1-13, 40MHz, 30dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_30DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [8] ESP_WIFI_REGULATORY_TYPE_MIC: Channels 1-13 (40M, 20dBm) + Channel 14 (20M, 20dBm) */
    {
        2U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_20DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
            { WIFI_REG_CHAN_MAX_14, WIFI_REG_CHAN_MAX_14, WIFI_REG_BW_20M, WIFI_REG_EIRP_20DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [9] ESP_WIFI_REGULATORY_TYPE_KCC: Channels 1-13, 40MHz, 23dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_23DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [10] ESP_WIFI_REGULATORY_TYPE_IFETEL: Channels 1-13, 40MHz, 20dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_20DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [11] ESP_WIFI_REGULATORY_TYPE_RCM: Channels 1-13, 40MHz, 30dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_30DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [12] ESP_WIFI_REGULATORY_TYPE_NCC: Channels 1-13, 40MHz, 30dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_30DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [13] ESP_WIFI_REGULATORY_TYPE_FCC: Channels 1-11, 40MHz, 30dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_11, WIFI_REG_BW_40M, WIFI_REG_EIRP_30DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [14] ESP_WIFI_REGULATORY_TYPE_GT: Channels 1-13, 40MHz, 26dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_26DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [15] ESP_WIFI_REGULATORY_TYPE_KE: Channels 1-13, 40MHz, 33dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_33DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [16] ESP_WIFI_REGULATORY_TYPE_KP: Channels 1-13, 20MHz, 20dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_20M, WIFI_REG_EIRP_20DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [17] ESP_WIFI_REGULATORY_TYPE_MY: Channels 1-14, 40MHz, 26dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_14, WIFI_REG_BW_40M, WIFI_REG_EIRP_26DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [18] ESP_WIFI_REGULATORY_TYPE_PK: Channels 1-14, 40MHz, 30dBm */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_14, WIFI_REG_BW_40M, WIFI_REG_EIRP_30DBM, WIFI_REG_DFS_DISABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
    /* [19] ESP_WIFI_REGULATORY_TYPE_TG: Channels 1-13, 40MHz, 20dBm, DFS enabled */
    {
        1U,
        {
            { WIFI_REG_CHAN_MIN, WIFI_REG_CHAN_MAX_13, WIFI_REG_BW_40M, WIFI_REG_EIRP_20DBM, WIFI_REG_DFS_ENABLED, WIFI_REG_RESERVED_ZERO },
        }
    },
};
